### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#100]
Not sure what happened. Trying to parse a set of records on PROD, I got this message:
> An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: /batch?id=14857&op=do StatusText: Service unavailable (with message) ResponseText:

> An error occurred while processing views_bulk_operations_active_queue_process with arguments: views_bulk_operations_active_queue_process

Something to do with this one record: https://nnels.ca/items/stalins-daughter-extraordinary-and-tumultuous-life-svetlana-alliluyeva

Part of the newest set of records: https://nnels.ca/admin/content/cals/records-sets/2015-12-new-requests-and-awards

When I skipped this one record, everything else worked just fine. Parsing just this one record will also throw the error.

Please note: I'm working on this set of records, so please do not reparse the whole set. Feel free to play with that one particular record though, or pull the whole set to dev/staging.

**Comment by davekisly** [comment]
I won't have time to review this before next week (earliest) but i've discovered a couple issues this afternoon working on #99, one with dates and the second with a (table of contents) description value. In each case, it was a matter of the marc tags including values too lengthy for the respective field type (the date field being more problematic). I applied truncation functions to both and then they parsed fine. I wouldn't be surprised were there being similar issues in what you are reporting here, perhaps related to enhancements to the date parsing ... anyway, that's what i'll check first when i get to this.

**Comment by Arty-chan** [comment]
This parsed okay after the update, but please make sure while working on #99 that we keep any fixes done.
