### ISSUE TITLE
Parsing & Displaying Edition Information

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#101]
Moved from Issue #99 

## Edition

Pull from MARC: 250 $a
Map to DC Relations: Qualifier: .isVersionOf / Value: info from 250$a, may need to strip ending punctuation but not crucial

Display on search results and title details just below Author using Label: "Edition:" whenever Qualifier is ".isVersionOf" (qualifier is not used for any other information)

**Comment by davekisly** [comment]
Just to confirm, is tag 250 being parsed appropriately? By "moving" this from issue 99, does that indicate its not working as expected? Perhaps you can test from here: https://dev.nnels.ca/admin/content/cals/repo-items/titles-alternate-uniform?keys=&field_xml_string_value=marc%3Adatafield+tag%3D%22250%22&field_access_restrictions_value=All&field_record_set_nid=All&field_title_alternate_value_op=longerthan&field_title_alternate_value=&status=1&sort_by=title&sort_order=ASC&items_per_page=50

Let's deal w/ the search / display as a distinct issue (it involves both indexing and css refinements) that we can resolve after we've nailed down the parsing?

**Comment by Arty-chan** [comment]
It looks like it's parsing to the correct place, but it should be stripping ending punctuation marks, such as " =" and " --"

**Comment by davekisly** [comment]
Those are not (strictly speaking) punctuation marks. Are u asking that we strip off all non-alphanumeric characters? Are there exceptions?

**Comment by Arty-chan** [comment]
Apologies, looking over the specs again, it looks like it's just the usual / or . at the end (unless it's "ed.") that needs stripping. Not sure why the one record has " --" at the end in the example set.

So it's mostly a matter of display that needs to be dealt with.

**Comment by Arty-chan** [comment]
> No problem folding edition (isVersionOf) into the Node Detail listing - i can do that fairly easily, i think. But, i'm wondering how important this is to include as part of the search results?
> 
> I ask partly because i think its going to incur a performance hit if go the easier approach (embedded view) or alternatively, it will require a fairly complex query to limit that field display to only "edition" details (while filtering out other possible DC Relations entries).
> 
> Part of the issue / complexity is that these values are managed thru a multi-valued field collection (DC Relations).
> 
> I happen to like these challenges and can probably figure out something that will work reasonably well, but at the same time, the "how important" question is worth asking when it comes to search results.
> 
> If it is important -and i can see there's some entries such as "Large print" that probably add valuable context- we might consider a slight restructuring to the content type. That is, instead of managing these entries thru the field collection, we attach a new field called "Edition" directly onto the node itself. This will streamline the query and help sidestep the need for funky embedded views / query alters.
> 
> We haven't really parsed many "edition" entries, so we're not going to lose much time / effort making this change now.
> 
> Thoughts? 

I thought about making edition a separate field, but would prefer keeping it as part of DC Relations if we can.

1) Edition is supposed to be part of DC Relations under DC guidelines.
2) Edition should be the only thing using the isVersionOf qualifier, so that should be a fairly simple filter? Correct me if I'm wrong.

We will definitely need to display this on the title details page. For search results, I was thinking we would display it if it's not empty (does that help performance?).

/cc @kpjorgen

**Comment by davekisly** [comment]
Its a "simple filter" within an embedded view, considerably less simple if pulled directly into the search api results view itself. 

So, for the time being, let's go w/ the first approach of an embedded view? It will possibly be less performant, but much easier to implement.

**Comment by Arty-chan** [comment]
How much of an effect would it have on search results performance? I 
already find our search to be slow...

If it has a big effect, then I'd rather move to the separate field option.

**Comment by davekisly** [comment]
it might not be noticeable, particularly if we ramp up the caching. So, i guess i would say adding an embedded view to display the Edition details will have an incremental impact (in the sense that _every_ field contributes something to the query / load) but in itself it may not have a huge impact. 

I would also guess the areas that incur the most overhead on the search results include i) the facet blocks, ii) the image loading (perhaps this is first-most?), and iii) the file listing (this being its own embedded view, i believe).

**Comment by Arty-chan** [comment]
Alright, so if edition itself has very little impact, then let's go 
ahead with embedded view.

**Comment by davekisly** [comment]
Ok, here's a preview:
- Node detail display: https://dev.nnels.ca/items/b-betsy
- Search Results: https://dev.nnels.ca/repository-search?search_api_views_fulltext_2=is%20for%20Betsy

As you'll see, the CSS needs tweaking in both cases. Do you want to do that?

**Comment by Arty-chan** [comment]
thanks. Looks good. Yes, I can take care of the CSS.

Can you push the display changes to staging? I'll restyle from there

**Comment by davekisly** [comment]
I just attempted to import the views so you can theme them, but unfortunately, the Search Indexes on Staging are out of sync with those of Prod and Dev. Its a bit tedious to sync those up manually (there's no import/export process i know of). I can do this later tonight. 

Alternatively, we can either i) refresh the database on Staging w/ a copy from Production (which should sync up the Search API index schema) and/or ii) you can do your theme tweaking on Dev?

**Comment by Arty-chan** [comment]
theming should be done, but we can ask @gitschatz to push the RWD branch up to dev as well to double check my changes

**Comment by Arty-chan** [comment]
parser parts done.

display:
* title view: done on staging
* search results view: on dev, to be pulled up to staging

**Comment by davekisly** [comment]
Something is killing the search on Staging. I'll troubleshoot, but in the meantime, here's an example of an edition statement: https://staging.nnels.ca/items/b-betsy

**Comment by Arty-chan** [comment]
Thanks. Edition statement looks fine on the title view, so it's just search that we need to make sure is styled correctly and such. Let me know when search is working again.

**Comment by davekisly** [comment]
I noticed Staging was a couple versions behind on various modules, so i updated half a dozen including search_api and search_api_solr. This seems to have resolved the white-screen, e.g. here's a search that includes an Edition statement: https://staging.nnels.ca/repository-search?search_api_views_fulltext_2=is+for+Betsy

**Comment by Arty-chan** [comment]
styling looks okay to me.

we can move it to PROD, unless @gitschatz or @kpjorgen has any concerns?

**Comment by gitschatz** [comment]
Adjusted the openlibrary covers link to use HTTPS on search results.

**Comment by kpjorgen** [comment]
Looks good — I’d say let it go up to Prod.


Kris Jorgensen
Project Coordinator, NNELS
https://nnels.ca
kris.jorgensen@bc.libraries.coop
Toll Free 1-855-383-5761 ext 1034
Cell 778-983-0203

**Comment by Arty-chan** [comment]
Has this been moved up to prod?

**Comment by davekisly** [comment]
No. I was going to ask about this during our meeting yesterday to clarify who should take this on (e.g., me or @gitschatz). Probably me i this case because there's a couple moving parts, but there's also a couple general module updates (e.g., search api) that should be run before i push the importer code and the updated views up. 

So, if its me to do this, i'll aim for the weekend when there's less traffic, etc.?

**Comment by Arty-chan** [comment]
latest version of parser pulled up to PROD

**Comment by Arty-chan** [comment]
I'd like to batch edit the edition. So, could I get a view where I could search for text within DC Relation as well as filter by qualifier?

Examples: refine list for "Unabridged" when the qualifier is "IsVersionOf" 
or for "reels" when qualifier is "IsPartOf"

It's fine if the batch edit operation is for "DC Relations" in general, same with the re-parse operation

**Comment by davekisly** [comment]
@Arty-chan, let me know if this does the trick? https://nnels.ca/admin/content/cals/repo-items/dc-relations-vbo

**Comment by Arty-chan** [comment]
Thanks. Yes, it does. The record set filter would be great to have as well.

**Comment by davekisly** [comment]
I've added the record-set filter.

You can replace / update each field selectively. Please test w/ one or two rows - easier to familiarize yourself w/ the actions that way vs. a lengthy description.

**Comment by Arty-chan** [comment]
Okay got it. Thanks.

Side note: Updated the spreadsheet in regards to DC Relation .IsPartOf

**Comment by Arty-chan** [comment]
schatz pulled related views to PROD.

**Comment by Arty-chan** [comment]
not sure what happened, but I don't see edition statement (Based on DC Relation, IsVersionOf) on the title details page anymore.

examples: 
* https://nnels.ca/items/essential-law-social-work-practice-canada-2nd-ed
* https://nnels.ca/items/race-and-ethnicity-canada-critical-introduction

/cc @gitschatz

**Comment by Arty-chan** [comment]
or if you can tell me what's the trick to only displaying values when the qualifier is IsVersionOf, I can add it myself...

**Comment by davekisly** [comment]
Do you have example entries on DEV you can point me to? Prefer to trouble-shoot this there...

**Comment by Arty-chan** [comment]
I couldn't find one on dev. Could be because edition wasn't parsed when the sync was last done, so I added it here: https://dev.nnels.ca/items/essential-law-social-work-practice-canada

**Comment by davekisly** [comment]
ok, well that helped. I recreated the Edition view on PROD: https://nnels.ca/items/essential-law-social-work-practice-canada-2nd-ed

**Comment by Arty-chan** [comment]
thanks, looks good. Not sure how this got lost previously.
