### ISSUE TITLE
Publisher File Only View

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#103]
Been trying to put a view together and got this far: https://nnels.ca/admin/content/cals/repo-items/publisher-only-titles

Unfortunately, that view doesn't do what we need it to.

What we need: only list the title if it has (PDF, EPUB2, EPUB3 OR AZW) but NOT(DAISY2, DAISY3, MP3, OR e-text).

Would also prefer if it only listed the title once, and list all available formats in the file format field (but file format field can be removed if that's not possible).

We have also been asked for a similar view where it has e-text but no audio (DAISY2, DAISY3, MP3). Not sure if that would be easier in one view (with above) or two separate ones.

Let me know if you need any clarification. Thanks.

**Comment by davekisly** [comment]
@Arty-chan - to confirm, this view as i've just modified it (per the screen-cap) **must exclude** the first row because that record does include a DAISY2 file, correct? Just want to double-check i understand the "but NOT" in your post above.

<img width="1215" alt="screen shot 2016-02-16 at 9 04 52 pm" src="https://cloud.githubusercontent.com/assets/852550/13097657/fa51d1f8-d4f0-11e5-9806-091e87ae3820.png">

**Comment by Arty-chan** [comment]
That's correct, first title should not be showing up.

**Comment by davekisly** [comment]
Based on my quick review of the query and an attempt to regenerate a simpler version of the view from scratch (https://nnels.ca/admin/structure/views/view/repository_items_publisher_listing/edit/page), the result are incongruent with how one would expect the "is none of" filter to work, echoing the issues described in this thread from 2-3 yrs ago: https://www.drupal.org/node/1529016

I'll look for solutions later today and if none work w/ Views directly, i can (probably) write a query alter to adjust the results.

**Comment by Arty-chan** [comment]
no wonder it didn't work when I tried it.

Thanks for finding that thread. hopefully something else work

**Comment by Arty-chan** [comment]
did you ever figure out a workaround for this view? Not a rush, but didn't want to lose track of this thread.

**Comment by davekisly** [comment]
Completely forgot about this one! :(

Will try to address in the next day or so.

**Comment by davekisly** [comment]
hi - have another look at this view: https://nnels.ca/admin/content/cals/repo-items/publisher-only-titles-2?items_per_page=500 

Does this seem to work as expected? Its rather convoluted (due to the number of table relations and subquery), but i think this currently filters out the requested formats.

**Comment by Arty-chan** [comment]
Thanks. This looks good, except I forgot to take Braille into account. Can the view exclude Braille from showing?

I imagine since this is a custom query we'll need a second display rather than simply being able to use filters, where it has e-text but no braille or audio (DAISY2, DAISY3, MP3).

**Comment by davekisly** [comment]
I could probably add two custom multiple select-list filters (e.g., "exclude-from" and "must-include") to emulate the functionality of a conventional views filter. Would that work better? If so, i'll have a shot at it this evening. I should be able to piggy back off the work i've already done.

If doesn't come together quickly, i'll add modify the first view display to exclude Braille and also set up a second display per your requirements above.

**Comment by Arty-chan** [comment]
either method is fine, so whichever is easier

**Comment by davekisly** [comment]
Well, no real luck on the fancier approach (facing a wall of code to implement this), so i'll have to revert to multiple displays. Will try to get this up for you later in the day.

**Comment by davekisly** [comment]
@Arty-chan, please review these three listings and let me know if this covers most of what you need here?
- https://nnels.ca/admin/content/cals/repo-items/publisher-only-items <- the most restrictive, excludes braille and etext
- https://nnels.ca/admin/content/cals/repo-items/publisher-only-items/no-braille <- excludes braille, includes e-text
- https://nnels.ca/admin/content/cals/repo-items/publisher-only-items/no-etext <- excludes e-text, includes braille

**Comment by Arty-chan** [comment]
thanks. Definitely looks like what we need.

One question, possible to show only unique node ID in results? When there are multiple files for a single title, I'm seeing it 2 or 3 times (as many as there are files)

**Comment by davekisly** [comment]
hi - a quick yes that's possible, but i notice the view is locked (by yourself) ... so here's how you can do this: 
- click on Advanced (right panel)
- under Other, click on Query Settings
- click "Distinct" - see screencap
- save view
<img width="968" alt="screen shot 2016-03-31 at 12 28 20 pm" src="https://cloud.githubusercontent.com/assets/852550/14183053/361bd1da-f73c-11e5-9bd7-35a70c51f4d5.png">

**Comment by Arty-chan** [comment]
weird, since I'm not even on the site

**Comment by Arty-chan** [comment]
updated access permission and added to appropriate place in NNELS Admin menu. Done.
