### ISSUE TITLE
Parser: Deal with Dates

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#104]
1) create view of problematic dates (non-numeric characters)
2) check that it's parsing what it's supposed to; spreadsheet for details on how it should be parsing

**Comment by davekisly** [comment]
hi @Arty-chan, to get the ball rolling, here's something i whipped up last nite / this AM: https://dev.nnels.ca/admin/content/cals/repo-items/dates-to-reparse
As a brief description:
- the view returns DC dates that include non-numeric characters. (As a caveat: I may need to refine the regex to return a broader result set.)
- the last column pulls out the tag values from the original xml string associated w/ tags 008, 264c, 260c, 533d and 534c. This is simply so we can view the source values to get a better sense of what we're dealing with. 
- you can try re-parsing the dates for selected items to see how well the parser works now. Bear in mind i haven't added any refinements in yet. (In some cases, these might be date fields that were parsed fairly early in the project.)

**Comment by Arty-chan** [comment]
I know that we recently sync'ed prod to staging, did we then do staging to prod? We don't need to, but a lot of the newer records are the one in RDA, which tend to be more problematic, so if you put the view on staging, it might pull up a significantly greater number of results. Not 100% sure, but fairly so.

**Comment by davekisly** [comment]
Here u go, i just pulled it up here: https://staging.nnels.ca/admin/content/cals/repo-items/dates-to-reparse

As a side note, overwriting the "XML String" required a bit of code that i added to the Importer module, so i can't replicate this view on PROD until we pull cals_importer up as well.

Again, i should emphasize i pieced this together v. quickly - i'm not absolutely certain the view is pulling back all the malformed date fields. If you know of ones its not pulling back, please point me to those so i can refine the view.

**Comment by Arty-chan** [comment]
It seemed to be pulling the right things, but after re-parsing they all disappeared... I mistakenly didn't load any of the records in a separate window to see what happened to the date after re-parsing, so maybe the parser on PROD is simply behind? maybe all we need on PROD is a reparse...

**Comment by Arty-chan** [comment]
latest parser on PROD along with view.

So did a bit of testing. This time carefully opening all the records in a new tab first. Results:
* generally okay, seems to be stripping non-numeric, which is great.

The problem is when there were multiple years or numbers in the subfield, which is not common, but happens in records (and correct, not human error).
Example: 1967, c1965. --> 19671965

Live examples:
* was "2000, 2001": https://nnels.ca/items/always-and-forever
* was "c1989, 2001": https://nnels.ca/items/broken-threads

**Comment by Arty-chan** [comment]
Oh, I also just realized, I didn't carefully check whether it sets the correct qualifier, only how it spits out the field data.

**Comment by davekisly** [comment]
Ok, i will review this further over the weekend. To clarify, will the date delimiter always be a "," (comma) or can there potentially be others?

**Comment by Arty-chan** [comment]
Generally, but you might also have the odd cases like these:
1968 [i.e. 1971] 
1878-[1927?]

**Comment by davekisly** [comment]
Are those examples rare enough that we might be better handling them manually, as one-off edits? Commas, pipes, colons, etc., are all pretty easy to treat as delimiters but these examples seem quite idiosyncratic to my Friday afternoon eye. Not easy to "parse", i suspect, unless these represent fairly common patterns.

**Comment by Arty-chan** [comment]
Yes, I would assume any multiple dates or full dates (including month year) to be delimited using a year

**Comment by Arty-chan** [comment]
examples of problematic dates (parsed April 8):
* https://nnels.ca/items/les-vacances
* https://nnels.ca/items/laventure-commence
* https://nnels.ca/items/la-myst%C3%A9rieuse-histoire-de-tom-c%C5%93urvaillant-aventurier-en-herbe

**Comment by davekisly** [comment]
I anticipate we'd be able to strip out non-numeric characters (e.g., dashes, ©, square brackets) - it seems we're already doing that partially. And i can add check for multiple values where the delimiters (e.g., commas) are predictable.

But i'm not really certain how i'd handle all the examples you provide. For example, what do we do with values like "1908-1924", "1968 [i.e. 1971]",  "1878-[1927?]?", etc. Do we grab a single value from these, multiple values.

if these patterns are relatively rare, i'd suggest handling them manually (either before they are added to Drupal or after parsing via the View i set up). Otherwise, we're apt to end up w/ a very dense date parser, which will incur more overhead when running and time/cost to develop.

**Comment by Arty-chan** [comment]
It's hard to catch before parsing because they validate. 

Is it easy enough to grab the first year (i.e. first group of 4 consecutive digits) which would handle the rare cases I provided as well)?

Otherwise, let's stick with stripping non-numeric characters, and make sure the view shows any dates with more than 4 numbers.

**Comment by Arty-chan** [comment]
I think the actual date is parsing correctly on PROD, however, the qualifier looks to be incorrect.

Records that I parsed in the newest set, all have 2016 Issued, however, since I believe it's pulling the year from 264$c, it should be 2016 Created

From the spreadsheet (but reordered)
264		$c		.created
260		$c		if 264$c not present; .created
533		$d		.created if not duplicate
534		From $c - possible?	.copyrighted 
008/07-10		.issued, if not duplicate year

**Comment by davekisly** [comment]
I haven't touched dates as of yet. The code is slightly more layered / involved, so i've been deferring work on this until i have a block of hrs to dig in (probably this weekend).

I do have some thoughts on the spreadsheet, however, which i'll send to you via email.

**Comment by Arty-chan** [comment]
okay, the code seems to be assigning .issued to the year from 264, so the code will definitely need tweaking.

note: slightly updated the list above

**Comment by Arty-chan** [comment]
so now that source fields are done, the above list of qualifiers should apply to the newest sets of records

**Comment by davekisly** [comment]
I've got some of this addressed on my local, but one question: can there be multiple "Created" values? 

When it comes to multiple values for Created and Copyrighted dates, the code currently retains only the most recent value (e.g., Created = 2014 is dropped if there's also a Created = 2015). Does this need to be amended (to allow for multiple values), and if so, does this apply to both Created and Copyrighted dates, or only the former?

**Comment by Arty-chan** [comment]
I realize, you're right that Created can have multiple values.

Copyright/Issued should not have multiple values

**Comment by Arty-chan** [comment]
and just realized that created should never have multiple values during parsing

**Comment by davekisly** [comment]
Re-reading your two most recent posts and want to confirm: 
- that neither of these date types (Created, Copyright, Issued) will contain multiple values?
- In cases where we do find multiple values for a given date type, are the rules for discarding the extra values the same across all three date types, i.e., retain the most recent date, discard the earlier ones?

**Comment by Arty-chan** [comment]
1) they shouldn't, though if I try to re-parse older records they might
2) correct.

**Comment by davekisly** [comment]
hi @Arty-chan, i've just pushed date-parsing refinements to DEV. Can you try reparsing a couple records (ideally ones w/ multiple dates, etc.) to see if the updates are in line w/ the requirements?

**Comment by Arty-chan** [comment]
Thanks, tested.

Noticed that the first if statement logic is there, but the second if statement for 533 is not. That is, 533 value will overwrite 260/264
> 264 $c .created
> 260 $c if 264$c not present; .created
> 533 $d if 260$c/264$c not present, .created

And this part doesn't seem to be implemented...?
> 534 From $c (publisher source) - possible? .issue unless it has a c in front, which case it's .copyrighted

**Comment by davekisly** [comment]
oops, i think i do have 534, but from $d (probably due to blindness from staring at marc xml). I'll address that tomorrow and re-commit along w/ the 533 fix.

**Comment by davekisly** [comment]
Do you have a record or two that includes 264, 260 and 533 values? I think i've addressed the relative prioritization (and you can test again, if you like), but it always helps to have real-life examples.

**Comment by Arty-chan** [comment]
I was testing simply by editing the MARC XML: https://dev.nnels.ca/items/politics-rights-lawyers-public-policy-and-political-change

I see that the code seems to be pulling from 534$c but it's marked it as .issued; possible (easy?) to implement the second part of 534$c logic?
> if it has a c in front, make it .copyrighted

**Comment by davekisly** [comment]
Well, the date parser did in fact push values thru a copyright checker ... but looking at the latter, it seems a bit off to my eye. 
- The original regex looks like this: "/^c\\d{4}/"
- i've replaced that with: "(c|C)\d{4}(\s|\.|$)" - this a bit more precise at the end of the string in looking for 4 digits followed by a space, a period or positioned at the end of the line. This ensures we don't inadvertently tag values like "c19999" as TRUE. This pattern is a tiny more flexible at the front of the string, allowing for both C and c (copyright) indicators.

Just re-parsed your example above and it seems good to my eye. Please test a few more and let me know if we need to tweak further?

**Comment by Arty-chan** [comment]
ah, I found a flaw in my logic.

originally I wrote this:
> 008/07-10 .issued, if not duplicate year

but here, what I meant by duplicate year is that if it does not duplicate any of the years (copyright, created, and issued)

For example, the 008 in this record duplicates the year from 264: https://dev.nnels.ca/items/1-dead-attic-after-katrina

If it's easier, we could do this instead:
> 008/07-10 .issued, if 534 $c does not exist

**Comment by Arty-chan** [comment]
ugh, and then I realized this applies to all records from accessible format producers (us, Crane, etc.) but not to purchased titles...

it all "hinges" on whether 534$c exists, so maybe it should be:

if 534$c exists, then
> 264 $c .created
> 260 $c if 264$c not present; .created
> 533 $d if 260$c/264$c not present, .created
> 534 From $c (publisher source) - possible? .issue unless it has a c in front, which case it's .copyrighted

if 534$c does not exist, then:
> 264 $c .issued, .copyrighted if it has a c in front of it
> 260 $c if 264$c not present; same as above
> 008/07-10 .issued, if not duplicate year

**Comment by davekisly** [comment]
ok, i was going to ask for clarification on the 008 notation. In any case, now that i've got the date parser refactored a bit, i should be able to accommodate this ok. I think i've updated my local, will test and then commit later this afternoon.

**Comment by davekisly** [comment]
@Arty-chan - snuck in one last commit drawing on our last discussion today. Didn't test extensively. If you have time, please test. Otherwise, touch base next week. Happy Canada Day.

**Comment by Arty-chan** [comment]
is it looking for existence of 534 or 534$c specifically? because it needs to be the latter

**Comment by davekisly** [comment]
Yes, it should be. See here: https://github.com/BCLibCoop/nnels-drupal-modules-cals_importer/blob/master/cals_importer.mappings.inc#L497-L498

**Comment by Arty-chan** [comment]
ah right, sorry, forgot we changed the logic (my brain was still stuck with the old logic).

When pulling from 008, is it looking at the specific string 07-10, because if I parse it, it ends up being a really long number.

Example: https://dev.nnels.ca/items/lady-batoche

**Comment by davekisly** [comment]
oh really? I must have messed that (008) up when collapsed some of the logic! I will remedy today and post back. Doh!

**Comment by davekisly** [comment]
ok, recommitted code on DEV which now parses that 008 correctly, i think (i.e., it gives it an Issued date of 2016).

**Comment by Arty-chan** [comment]
looks good

**Comment by Arty-chan** [comment]
Closing. Assume this will be pushed to prod with #121
