### ISSUE TITLE
Parser: Source Fields: Publisher

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#105]
Not sure if we should split the source fields into multiple issues, but let's start with Source: Publisher.

As mentioned in #104, right now MARC records are uploaded based on the existing mapping, to ensure that moving forward we have the correct qualifier for the matching date, I'd like to add the Source: Publisher field.

As per the spreadsheet, I recommend a text field which would take 534$c as is, which includes publisher location, name, and year (optionally stripping trailing punctuation, usually a period).

For reference, other 534 subfields usually include $z (going to Source: ISBN (the current ISBN field)), $e (physical description, current mapping to DC Relation IsFormatOf), and will start with $p (some descriptive text, like "Original version")

**Comment by Arty-chan** [comment]
JFYI, the Crane records mostly have 534; and the latest set of records on PROD is how I'd expect NNELS ones to typically look like: https://nnels.ca/admin/content/cals/records-sets/2016-04-requests-and-griffin
(unless I missed something in the MARC editing step)

**Comment by davekisly** [comment]
Ok, good to have sample record-sets. Pulling this down to my local. Should have this parser refinement implemented (on DEV) by Monday.

**Comment by davekisly** [comment]
Have a look at this record-set and let me know if its parsed the 534c tag as expected?  https://dev.nnels.ca/admin/content/cals/records-sets/2016-04-requests-and-griffin

The Publisher (Source) field is (temporarily) appended to the bottom of each node detail page, e.g.,: https://dev.nnels.ca/items/tell-poems-girlhood

**Comment by Arty-chan** [comment]
looks fine to me

**Comment by davekisly** [comment]
I've pulled the parser updates to PROD and modified one of our earlier views used to re-parse selected fields so you can zero in on the Source.Publisher field:

https://nnels.ca/admin/content/cals/repo-items/titles-alternate-uniform?keys=&field_xml_string_value=&field_access_restrictions_value=All&field_record_set_nid=67627&field_title_alternate_value_op=longerthan&field_title_alternate_value=&status=All&sort_by=title&sort_order=ASC&items_per_page=50

The parser removes trailing punctuation (for the most part), but leaves most of the remaining tag as is. So, as you'll see in the first two examples above, it does not strip out square brackets. If you want this done as well, i can tackle in conjunction w/ some of the date parsing refinements?

**Comment by Arty-chan** [comment]
any other cleanup by the parser is optional. It's not a field I anticipate indexing, linked, etc. so if it would slow the parser down, let's leave it as is.

Will take a look and do some testing.

**Comment by Arty-chan** [comment]
parsed a few, and now starting to re-parse all of the Crane records. This looks good.

**Comment by Arty-chan** [comment]
Note: I've marked this to be displayed, but let's do that after we get the other Source fields done.
