### ISSUE TITLE
Parser bug: ISBN has non-valid characters/trailing punctuation

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#106]
Based on the parser that is up on PROD (which I assume is the latest version), it looks like the parser is not stripping punctuation and other things after the number. I generally try to strip it from the MARC record, but that doesn't always happen.

Example: https://nnels.ca/node/67498/
> 9782266185813 :

Colon is the most common in terms of punctuation, but it may also have other information after the ISBN, such as:
> 0385133553 (v. 2)

**Comment by davekisly** [comment]
Not sure stripping out non-numeric characters was ever part of the initial design - perhaps we assumed infallible data at source. :) Also, i don't think we spent much time adding parsing logic on fields that are not visible (to the general public) and/or which don't really impact search-ability. E.g., if you search for "9782266185813" you can still retrieve the record that includes "9782266185813 :"

So, yes, we can strip out all non-numeric chars at parsing time. But, is there a downside to leaving them "as is"? If yes (there is a downside), i'll tackle this in the next round of parser enhancements.

**Comment by Arty-chan** [comment]
Easier to strip ending spaces/punctuation or simply strip non-numeric except "x" (or X)?

Our book covers are tied to that ISBN field, so I can only assume that it needs an exact match for the book cover to show. If that's not the case, then you're right, we could leave it as is.

**Comment by Arty-chan** [comment]
Okay, sorry, I just realized that for ISBN, I have a note to strip punctuation and the like before parsing, but again because I believe it's tied to book covers, I think it would help if we could run a one-time thing on existing ISBN.

**Comment by davekisly** [comment]
ah yes, good point re. the image linking. Ok, will (aim to) address this week.

**Comment by davekisly** [comment]
Ok, i've tightened up the ISBN parsing to strip out any / all non-numeric characters. Here's an example on DEV, which has a bunch of non-sense chars added to the ISBN tag, i.e., "xyz 9782266185813 : bubble tea, igggger 0782266185814": https://dev.nnels.ca/node/64263/edit

It strips those away and adds two ISBN entries: 9782266185813 and 0782266185814

Please test more thoroughly and let me know if this does the trick?

**Comment by Arty-chan** [comment]
X and x are valid characters in ISBN though...

**Comment by davekisly** [comment]
ah yes, overlooked that point. I'll commit a refinement this evening.

**Comment by davekisly** [comment]
Do you want this to also validate for string length and the positioning of the X|x character? e.g., the string must be either 10 or 13 characters in length & x's should only fall into the last position?

And if yes, you do want that validation added, should we skip over ones that fail (not add their values to the field)?

**Comment by Arty-chan** [comment]
Makes sense that if we're going to do validation, we might as well chuck whatever doesn't fit. We can just stick with 10 or 13 characters (we can skip validation of position of x, though whatever is easier).

While people can search by ISBN, it's mostly used for book covers, so validation is not as important as trying to parse whatever information is provided.

If simply stripping non-numeric except 'x' is easiest/fastest, then we can leave it at that. My MARC editing script should be removing most things anyway (trailing spaces and punctuation is the only thing that it might accidentally leave around, though I'm trying to get rid of those too).

**Comment by davekisly** [comment]
Stripping x is the simplest / fastest, but if we are also validating on string-length, then its really not much extra to preserve the x's when they are the right-most character on 10 or 13 character strings. I've already got something worked out on my local, so i think we're good there.

**Comment by davekisly** [comment]
hi @Arty-chan - pls have another look at https://dev.nnels.ca/items/laventure-commence and let me know if this is working as expected? 

To test thoroughly, you can edit the MARC XML string, save and then press Parse MARC again.

**Comment by Arty-chan** [comment]
looks good to me

**Comment by Arty-chan** [comment]
I assume this has been pushed up to PROD. Closing.
