### ISSUE TITLE
Parser: (Source Fields:) ISBN

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#107]
As discussed, the ISBN part of the Source Fields group should actually be the existing ISBN.

In the identifier area should be a new ISBN field (ISBN_audio?) which pulls from 020.

The latest MARC record set of PHP audiobooks is a good example: https://nnels.ca/admin/content/cals/records-sets/php-2016-04-full-catalogue

Also good examples are the RBdigital sets

Will also need to re-parse existing records to copy 020 into the new ISBN field.

**Comment by davekisly** [comment]
@Arty-chan - i haven't looked at many records, but it seems we should be parsing 020 where the subfield is "a" - is that correct? Or, is it any 020 tag?

**Comment by Arty-chan** [comment]
apologies, didn't specify here (though it's in the spreadsheet).

Correct, 020$a ; should also go through the same validation as the ISBN (source) field

**Comment by davekisly** [comment]
ok cool, i'm finished that on my local and have just committed the parser update to DEV along w/ a test record-set that you can test with here: https://dev.nnels.ca/admin/content/cals/records-sets/php-2016-04-full-catalogue

The ISBN (Audio) field is temporarily positioned to display below the MARC record field on the detail node. 

If your test goes well, i'll commit this to PROD later this evening.

**Comment by Arty-chan** [comment]
Yeah, looks good. Let me know when it's up on PROD, then I can re-parse the ISBN_audio for that record set on PROD

**Comment by davekisly** [comment]
Ok, i've pulled it up to Prod. Will follow up, if/as required, over the weekend.

**Comment by Arty-chan** [comment]
thanks will test with the PHP record set

**Comment by Arty-chan** [comment]
the parsing looks good.

As to display, the ISBN_audio should be displayed along with the rest of the title details (rather than below the MARC XML box), and simply labelled "ISBN", all on the same line, separated by comma. I can reorder and do styling if necessary, once it's in the right block.

**Comment by davekisly** [comment]
For clarification, 
- what position do you want the ISBN displayed in relative to other fields on the display? E.g., after language?
- Is the intent to display only the audio isbn values? Or, do you want to display ISBN values from both fields?

**Comment by Arty-chan** [comment]
1) it's not super important, so after language is good
2) Audio ISBN only, hence why I would like to use the label "ISBN"

Side note: While I plan to display the source publication information, I don't plan to display much (if any) of the other source information. The original ISBN will purely be used for book cover images. Might consider displaying it to staff in case we want to troubleshoot book covers, etc. but definitely not to patrons/public.

**Comment by davekisly** [comment]
Which server should i add this to, DEV or PROD? I'm not certain there's any published entries with Audio ISBN values, so it might help if you were to publish a couple records before i update the view.

**Comment by Arty-chan** [comment]
not sure about staging/dev, but on PROD all the RB Digital titles should have audio ISBN since I reparsed that field.

examples:
* https://nnels.ca/items/illegal-0
* https://nnels.ca/items/skeleton-tree
* https://nnels.ca/items/all-my-puny-sorrows
* titles from: https://nnels.ca/admin/content/cals/records-sets/rb-digital-dec-2014-batch-part-1 (or part 2 or part 3)

since the ISBN audio field is already on PROD (under the MARC XML box), you could just make the changes there

**Comment by davekisly** [comment]
Ok, i've added the ISBN (audio) field into the view. Needs a tiny CSS touch-up, will leave that for u.

**Comment by Arty-chan** [comment]
looks good. Thanks. Will take care of CSS tweaks

**Comment by Arty-chan** [comment]
css tweaks committed. Ready for @gitschatz to pull him whenever he feels like it.
