### ISSUE TITLE
Parser: Source Fields: URI

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#108]
The parser currently maps 856$u to the URI field.

Ideally, we would change the URI field to actually be two parts: actual URL, and display text
e.g. http://gutenberg.org/idnumber ; Project Gutenberg

856$u (when first indicator is blank (non-numeric) or 4) would still map specifically to the URL part of the URI field. $3 if it exists would map to the display text portion.

Notes:
After parser implementation, will need a view to do cleanup; also need to look for any links marked with "(free)", or "gutenberg" in the commercially available links area and move them to the URI field.

**Comment by davekisly** [comment]
Are there a finite number of "text" values here? I can, as you suggest, grab $3 values, but i'm wondering if we should instead match URL patterns to a normalized taxonomy?  Doing so, we could potentially link records that share a common parent catalog / source (etc.).

Here's a quick listing i tossed together of items that include URI values: https://nnels.ca/admin/content/cals/repo-items/source-urls

If there's simply too many discrete / unique patterns, it might be easiest to simply parse the $3 values, but i thought i'd raise the possibility above as it would influence the field structure somewhat.

**Comment by Arty-chan** [comment]
there are definitely a couple of sources that would be very common; namely Gutenberg and Librivox. And right now, I believe there are a couple of government document sources, while it wouldn't be a huge number, the list could grow (particularly in government documents). And I admit, $3 is a "great if someone fills it in" but most cataloguers don't fill it in.

So if we could do URL pattern matching, that'd be great and save me a lot of time. We could drop parsing $3 altogether in that case, and have a view that lists URI and the related text field (similar to what you already have), with the ability to filter for text fields that are blank.

match:
* "gutenberg" ; text: Project Gutenberg
* "librivox" ; LibriVox

In the interim, could I get a view where I could edit the individual URI fields? I'd like to delete all the gutenberg license, loc, and nnels links.

**Comment by davekisly** [comment]
thanks for the reply. Heading out for the evening, but i've updated the view to include a bulk operation that allows you to RESET the URI. You could, i guess, set the value to blank (null). I think that should delete the values. Test with one or two first and go from there.

https://nnels.ca/admin/content/cals/repo-items/source-urls

**Comment by Arty-chan** [comment]
thanks. That works if I want to empty all the fields in the URI, but most of the gutenberg license links are with a link to the gutenberg ebook. However, I only want to get rid of the license link. The view we build to maintain URI in the future will also have to allow bulk editing of individual sets of link + display text

**Comment by davekisly** [comment]
To my knowledge, the view you are describing (changing 1 value in a multi-value field) will not work out of the box. Maybe there's a VBO add-on module that will facilitate this, but it may end up i'd need to write a custom action script to do this. That's not a huge deal, just that it doesn't exist out of the box, and secondly, it might be better to work on this after we've figured out the new "normalized" URL qualifier field. 

One thought, perhaps an alternative to the above: are there URIs patterns that should be completely skipped over when parsing MARC XML files (e.g., ones w/ the word "license")? 

If yes, perhaps we should add these into the script that parses URIs to ensure these URIs are never added in the first place? If we did that, then you could simply search for those patterns (using the filters in the view above), and then re-parse the URI field for the selected records. 

if there's a finite number of patterns to always ignore, then this might be the quickest way to addressing this particular side-issue.

**Comment by Arty-chan** [comment]
other than license

* anything with "loc.gov"
* "nnels" links (for re-parsing purposes)

that's all that I can think of that we would consistently not load. It's not often that we would have URIs in the first place

**Comment by davekisly** [comment]
Quick note to confirm that the URI parser skips over all values containing "license", "loc.gov" and "nnels", so you should be good to test this on DEV, at least. You can filter records by adding one of those stop words to the URI field, e.g., as follows: https://dev.nnels.ca/admin/content/cals/repo-items/source-urls?keys=&field_xml_string_value=&field_access_restrictions_value=All&field_record_set_nid=All&status=All&field_uri_value_1=license&sort_by=title&sort_order=ASC&items_per_page=50

When you re-parse the URI, those entries should be stripped out.

I don't believe this has been pushed to PROD yet, but will be included in the next update (e.g., the Literary Format update).

**Comment by davekisly** [comment]
Going back to the posts on April 22 re. matching records w/ gutenberg and librivox URL patterns to their contributor names, I'm trying to determine what sort of field that will be and what the overall intent in splitting the URI into discrete bits will be.

As to the field type, examples include: 
- we could set it up as a new taxonomy term (e.g., "Contributor").
- alternatively, we could re-use the "Organization" node-reference field already being used when adding S3 attachments. All the latter would require is ensuring that we add entries for Project Gutenberg and Librivox (etc.) and the parser correctly matching to the respective org-id. 
- or, we could re-use the DC publisher field, as many of those are (i think) already populated w/ Project Gutenberg
- or we can bypass all the approaches above by "theming" the identified URL patterns with the preferred labels.

I think the "best" approach depends a little on the end-goal. Your first post mentions "... $3 if it exists **would map to the display text portion**." To my recollection, tho, we don't actually display any URLs in the search / result interface (do we?). Is the aim in this ticket to change that, i.e., to include URLs in search results and/or on detail records? 

If yes, what is the associated action when a user clicks on "Project Gutenberg" (for example)? Should the user be sent to the external record at the contributor's site? Or, would we direct her to a page on our site that operates like a pseudo result screen (listing all the records for Project Gutenberg)? Knowing this will help me narrow down the best field type.

**Comment by Arty-chan** [comment]
The main reason to have this field is to direct someone to the free, online source if applicable; so we would display the link on the title details page, and if clicked on it, the user would be sent to the relevant page on the source website.

Something like:
Example Title
We have DAISY202
Source: Project Gutenberg (which links to the gutenberg files page of the Example Title)

I imagine it to be similar to the commercially available field (collection?) except that on both the staff and user side, it will display with other source information on the title details page.

**Comment by Arty-chan** [comment]
also tested on dev, looks fine to me.

**Comment by davekisly** [comment]
Ok, if the link is likely to go to Gutenberg's site (not to a default "result" page on nnels) i will suggest we migrate to a simpler "link" field (https://www.drupal.org/project/link). 

The current URL field was originally set up as a simple text field (mostly b/c i didn't have a good sense of what types of URLs and strings would be pulled from the MARC records). 

Drupal's link field type, however, gives us an option to split the title and the URL, and has (i assume) less overhead than managing this as a Field Collection. (Field Collections are great where we need compound fields, but seem overkill here since we're not really doing much beyond listing the Source as part of the outbound URL.)

If you're uncertain about this, let's talk via Skype Thurs or early next week? On the other hand, if the approach sounds appropriate, the next step would be to write a script to copy the current URL entries onto the new field, which i can probably wrap up by this weekend, and then to update the parser.

One question if we do go ahead w/ this. What should the default "Source" entry where the URL doesn't originate from the 2-3 values u have indicated above? Just add the URL? Or, some other generic text?

As a side point, we could also at some point leverage Drupal's Link Checker module to track 404's and the like (e.g., see: https://www.drupal.org/project/linkchecker).

**Comment by Arty-chan** [comment]
link field is fine. (I only mentioned field collection since I wasn't sure what the options were.)

If it doesn't match one of the values we have, we can leave the text part empty (and from what I read, it'll just put in the link itself as the display text by default)

**Comment by davekisly** [comment]
Think i've got most of this figured out. Longer explanation later, but in the meantime, have a go at parsing the External URL field: https://dev.nnels.ca/admin/content/cals/repo-items/source-urls?keys=&field_xml_string_value=&field_access_restrictions_value=All&field_record_set_nid=All&status=All&field_uri_value_1=librivox&field_dc_contributor_value_op=contains&field_dc_contributor_value=&field_dc_creator_value=&field_publisher_value=&sort_by=title&sort_order=ASC&items_per_page=50

**Comment by Arty-chan** [comment]
looks good.

note that we'll (probably) want to remove the URI field, replacing it with the external URL field

**Comment by davekisly** [comment]
agreed re. URI. 

Should i move the parser updates and corresponding view up to Prod?

**Comment by Arty-chan** [comment]
yeah we should be good to go on it

**Comment by davekisly** [comment]
Ok, i've just pulled it: https://nnels.ca/admin/content/cals/repo-items/source-urls

**Comment by Arty-chan** [comment]
thanks.

how do you suggest we proceed with removing URI?

**Comment by Arty-chan** [comment]
also, I guess we should add to the automated text generator
* archive.org = "Internet Archive"

**Comment by davekisly** [comment]
Once you've parsed all the URL fields, then I can pull URI and remove it from the parser, etc. (There's no issue retaining it for now.)

As to additional labels, do you anticipate finding many others? 2-3 normalized labels are easy to manage in the way i've set it up now, but I don't want to turn this parser into a spaghetti code of if-statements. So, if this is likely to be an on-going discovery process, i'd suggest we add functionality that allows you to add new entries, similar to other normalization options, via the UI interface here: https://nnels.ca/admin/config/cals_importer/normalization

Let me know what you think is best here.

**Comment by Arty-chan** [comment]
I don't _think_ there will be any more really. The rest will likely be manually done, but at the same time, if it's easy to do, I think it would be a lot better to be able to add new entries via UI interface rather than directly in the code

**Comment by davekisly** [comment]
It will take a bit of work (an incremental amount), but the benefit is more flexibility and sparing you having to wait for code-updates if/as you discover new patterns (as you add new record-sets, for example). So, yes, i'll proceed on that refinement in the next day or so.

**Comment by davekisly** [comment]
@Arty-chan - when u have a chance, can you revisit the parsing on DEV? Specifically, go to the config options first at the bottom of this page, i.e., the text fields for adding matching patterns and exclusion patterns: https://dev.nnels.ca/admin/config/cals_importer/normalization - tweak those (follow the examples), and then see if this works as expected?

**Comment by Arty-chan** [comment]
looks good. thanks

**Comment by davekisly** [comment]
hi - i've just pulled the update to PROD and copied over your config tweaks: https://nnels.ca/admin/config/cals_importer/normalization

One small point is i didn't really test for potential wildcards (e.g., periods, slashes), so you might want to test those entries that include patterns like "/archive.org" just to ensure its working as expected.

**Comment by Arty-chan** [comment]
that's what I was specifically testing for this time around. I didn't want to just put archive.org in case there was something like internetarchive.org so I put in those two entries and they worked as I expected.

now that this is done, we'll probably want to deal with displaying as per #109 but I might take care of this myself if I can make it do what I want.

Can you make sure any recent new field(s) are on staging? I don't need the latest parser per se, but usually deal with title details display changes and CSS testing there (thus why I need the fields)

**Comment by davekisly** [comment]
Ok, good to hear on the parsing.

As to syncing up Staging, I think it would be better to refresh the database on Staging w/ that from Production. Otherwise, i have to manually inspect each of the relevant content types, etc. On most sites, i could use Bundle Copy to sync up the content types, but there's a couple custom fields (e.g., Cors 3) that stymie this process. As well, I've been having intermittent problems w/ my ssh keys sticking on Staging, so i'll admit to bypassing Staging on the latest set of admin-only updates (e.g., parser related).  

So, my recommendation is to run as much of the parsing as you can on Prod, get Jonathan to run any security / module updates that are required on Prod, and then copy over the DB from Prod to Staging. If Jonathan's tied up, i can do this next week some time.

Going forward, perhaps we should shift to Features, as these give us a way to export database configurations (e.g., field changes) from one site to another. But, for the time being, a database refresh might be the quickest.

**Comment by Arty-chan** [comment]
we did a sync recently, so the only fields I'm missing on staging that I can tell is the External URL from this issue and ISBN (audio). I don't need them populated. I can do that manually just to see what the display would look like.

**Comment by davekisly** [comment]
I won't be on Staging for the next couple days, so why don't you do your theming updates on DEV? At this point DEV is closer to PROD (in terms of views / field structure, etc.) and in any case, its the better location to carry out development work (inc. theming).

**Comment by Arty-chan** [comment]
note: done reparse
