### ISSUE TITLE
Parse Bug? Control number not always being pulled from 037?

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#110]
I just noticed that most of the records in the PHP set are missing control numbers:

oddly the first one has it: https://nnels.ca/items/business-baby-what-doctors-dont-tell-you-what-corporations-try-sell-you-and-how-put-your

but the others, such as this one do not: https://nnels.ca/items/harperland-politics-control

both have 037$a and same indicators

set: https://nnels.ca/admin/content/cals/records-sets/php-2016-04-full-catalogue

**Comment by davekisly** [comment]
hmm, have a look here: https://github.com/BCLibCoop/nnels-drupal-modules-cals_importer/blob/master/cals_importer.mappings.inc#L707

Basically, this function is returning null values when there is no 035 tag, which is probably not correct and possibly a reflection of the fact that this is something both Jonathan and i worked on (at different points). I will rework this, but need some guidelines / confirmation of what exactly should happen.

I recall we were to use the 035$a where available and if not, use the 037$a (as echoed in the inline note "fallback to 037 when 035 isn't present"). But, this is a v. vague recollection and your spreadsheet indicates using 035 for OCLC and 037 for sys control numbers. Should i amend this function in line w/ the spreadsheet's directive?

**Comment by Arty-chan** [comment]
spreadsheet is correct. 035$a should translate to OCLC number (and if it's not a valid OCLC number, just ignored, which I remember we have validation for already).
sys control number should be pulled from 037$a "as is" (they're not supposed to have any punctuation, so I'm going to assume we don't need to strip anything)

The only concern I might have is if we ever reparse old records, because the older MARC records were edited to put the sys control num in 035$a

**Comment by davekisly** [comment]
ok, makes sense and in turn, i'm going to split the current function into 2 discrete functions, one for sys numbers, the other for oclc. 

Re. parsing old records, maybe the best idea there might be to use the "re-parse" operation and simply ensure those fields are not included?

**Comment by Arty-chan** [comment]
yeah, that's fine. I'll add a note to the spreadsheet that we should not re-parse sys control number for older records

note: after the fix, we will want to re-parse sys control number for any Crane, RBdigital, and PHP records where sys control number is currently blank

**Comment by davekisly** [comment]
ok, i've got this working on my local. Will move up to DEV a bit later today.

**Comment by Arty-chan** [comment]
hi @davekisly is this moved up to dev or prod? I was hoping to load a bunch of files today/tomorrow, but obviously need the control numbers (in the new PHP set) before I can do that

**Comment by davekisly** [comment]
No, not yet. Will pull to DEV tomorrow AM for testing. Maybe copy the record-set(s) you want to parse so you have good data to test with?

**Comment by davekisly** [comment]
Also, if you want to get these records up on PROD asap, you do have the option of parsing them as is and then re-parsing the sys control numbers once the importer updates are pulled up.

**Comment by Arty-chan** [comment]
they're already parsed, but sys control numbers are needed if I'm going to do batch s3 path update...

**Comment by davekisly** [comment]
Try the set on DEV and let me know if it works as expected: https://dev.nnels.ca/admin/content/cals/records-sets/php-2016-04-full-catalogue

If all is well, i'll commit to PROD later in the day.

**Comment by Arty-chan** [comment]
I assume nothing else has really changed at this point. Sys control number is parsing as expected.

**Comment by davekisly** [comment]
Well, actually, there are a few changes: first, i split up what had originally been one script into two discrete ones (one for sysnums and one for oclc nums), so it would be good to confirm that both those fields (inc. oclc) are parsing correctly. 

Not directly related, i also added a couple helper functions that facilitated moving redundant looping code from a number of other functions. (ref: https://github.com/BCLibCoop/nnels-drupal-modules-cals_importer/blob/master/cals_importer.mappings.inc#L207-L250)

Finally, I also removed some code i had flagged as deprecated (or which wasn't being called anymore).

I've tested incrementally on my local (nothing broke to my eye), but its always good to get a secondary review before we move up to PROD.

**Comment by Arty-chan** [comment]
OCLC number seems to be parsing correctly as well

**Comment by davekisly** [comment]
kk, i'll pull up to Prod shortly.

**Comment by davekisly** [comment]
ok, its now on PROD.

**Comment by Arty-chan** [comment]
great, thanks!
