### ISSUE TITLE
Update file size function no longer working?

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#112]
Not a rush, but find this odd since this was working just a week or two ago, so not sure what happened:

I used this view and the function on it to update the file size on the PHP batch of files: https://nnels.ca/admin/content/cals/files/filesize

but file sizes are not showing. Example: https://nnels.ca/items/everyday-bias-identifying-and-navigating-unconscious-judgments-our-daily-lives

Note: when adding files individually using the "Update file attachment" function/link on the repo item page, it seems to work fine. Example: https://nnels.ca/items/wild-adventures

full list of titles: https://nnels.ca/admin/content/cals/records-sets/php-2016-04-full-catalogue

**Comment by Arty-chan** [comment]
Okay, not sure exactly what's happening.

Was adding this title today: https://nnels.ca/items/sweetest-kulu

1. Used the "Create attachment from s3 path". Created DAISY link with no file size.
2. Added "e-text" file using the "Add" (attachment) button. DAISY link suddenly had file size.
3. Added "PDF" file using the "Add" button.
4. Clicked on the "Update file attachment" for "e-text", then for "PDF". No file size on either. Both of these do show up on the "update filesize" view (which I have not yet updated so you can see them).

What's weird though is that the DAISY link didn't have the file size after creation, only after I created the second attachment.

Thought this might provide insight into the original reported problem.

**Comment by davekisly** [comment]
haha, that's pretty weird. Part of this might be cache (e.g., on the view) and how the size is gathered from externally stored files. I will poke around tomorrow to see if i can make headway on this.

In the meantime, i just ran the "update filesize" view.

**Comment by Arty-chan** [comment]
checked cache on the block, which says none. I can't imagine it'd be cache on the view, even if it does have it, I don't think anyone's changed it recently

**Comment by Arty-chan** [comment]
did you change something? It looks like they all have file sizes for now. If you change something, could you please add a comment to document what you did?

Will close for now since it seems fixed. Will re-open if I'm still finding issues next time I add files.

**Comment by davekisly** [comment]
yes, i generally do comment on things i've revised ... which is to say no changes to this point. 

Re. the caching question, there's caching in different places, inc. the view(s), sometimes blocks, there's page caching and perhaps (i don't know as i'm not the admin) also server cache / proxying (varnish, memcache, etc.) and whatever caching exists on the s3 server. That's not to say our issue here is caching, just not ruling out the possibility. 

The code itself for updating file-sizes is pretty "simple" on our end, but it relies on a lot of black-box (to me) cors s3 functionality, which involves instantiating a stream wrapper and grabbing the file size from that wrapper. If there's some sort of communication / network issue (or, again, a cache/proxy setting), then the wrapper will return null values. I recall (vaguely) this sometimes happening back when we set everything up and in those cases, often the "fix" was to re-run the process.

So, keep an eye on this and we'll go from there.
