### ISSUE TITLE
Parser: Literary Format

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#113]
Now that we've got this completely cleaned up, I want to make sure this is coded as it should be. 

This might take all of a few minutes to make sure the code does what it's supposed to, but I would like this checked before I parse any new records since we _just_ finished cleaning this up.

Based on 006/16 or if 006 not present, 008/33
0 - Non-fiction
1 - Fiction
d - Dramas
e - Essays
f - Novels
h - Humor, satires, etc.
i - Letters
j - Short stories
m - Mixed forms
p - Poetry
s - Speeches
u - Unknown (leave as default, not specified)
| - No attempt to code (leave as default, not specified)

**Comment by davekisly** [comment]
By "just cleaned up", do you mean in the source files? Or somewhere else?

In any case, i don't see (in my quick grep thru the importer) anything that explicitly parses 006. Also, can you explain 006/16 - is that the 16th character? Just noticed your spreadsheet (at least my local copy) mentions this as a future implementation ... is this a to be implemented next feature?

**Comment by davekisly** [comment]
oops, scratch that question re. 16th character (which is confirmed here: http://www.loc.gov/marc/bibliographic/concise/bd008b.html)

**Comment by Arty-chan** [comment]
the "future" note on the spreadsheet is under the "display" column, that is we may display it in the future, but we do not at the moment.

"just cleaned up" as in setting the literary format for items in the repo...

My understanding was that this was already implemented, though possibly only based on 008 at the moment

**Comment by davekisly** [comment]
I don't think it was implemented at all. There's a placeholder field for it in Drupal, but i don't see any explicit reference to it in the parser.

**Comment by Arty-chan** [comment]
oh, in that case.... I guess this will be a feature implementation. I hope this one is fairly straight forward.

Let's move this ahead of #108 (since URI rarely shows up in MARC records anyway)

**Comment by davekisly** [comment]
Do you have any record-sets (or individual records) that include a good sample of these sub-fields (006/16 & 008/33)? Can you add to DEV and/or point me at 'em?

**Comment by Arty-chan** [comment]
unfortunately no. All records will have 008, some will have 006, but even when they do, it's frequently not coded. Manually changing some of the records on dev is the best I could do I think.

**Comment by davekisly** [comment]
Once the mysql file-space issues are resolved, it would be great if you could give me a couple samples (manually-edited or not).

**Comment by Arty-chan** [comment]
Manually edited a few:
* Purposely coded as Essay in 006 and Non-fiction in 008: https://dev.nnels.ca/node/63268/
* both coded as non-fiction: https://dev.nnels.ca/node/57196/
* both coded as fiction: https://dev.nnels.ca/node/51904/
* no 006, 008 coded as fiction: https://dev.nnels.ca/node/51940/
* no 006, 008 coded as novel: https://dev.nnels.ca/node/51913/ & https://dev.nnels.ca/node/51898/
* Has no 006 or 008, should not set literary format value: https://dev.nnels.ca/node/13867/

Let me know if you need more examples.

**Comment by davekisly** [comment]
that's great, thanks. Will pull these down to my local tomorrow AM and test then.

**Comment by davekisly** [comment]
hi @Arty-chan - think i've got this worked out, will update DEV's parser soon for you to test. One question first: our current default for this field is "None", Drupal's typical default on single value select field of this sort. The MARC 21 Format for bib data includes "u" ("unknown") or "|" (no attempt to code) as possible entries. Would it be safe to map these to "None"? Or, are "u" and "i" values distinguishable from "None"?

**Comment by Arty-chan** [comment]
Sorry if the first post was not clear on this. Yes, if it's u or |, you can leave as Drupal's default none.

**Comment by davekisly** [comment]
ok, i've just committed the parser updates to DEV. Can you run thru each of the items you modified above (press parse marcxml) and review the Literary Format field to ensure this is working properly?

**Comment by Arty-chan** [comment]
looks good. Correct value came up for all of them.

Also, I think we can remove "Unknown" from the list.

**Comment by davekisly** [comment]
Ok thanks for confirming. Will remove Unknown on PROD when i commit the latest parser there.

**Comment by Arty-chan** [comment]
curious, has this been moved up to PROD?

**Comment by davekisly** [comment]
no, not yet. While the records you parsed seemed ok, i ended up doing further testing on Thurs via this new view here: https://dev.nnels.ca/admin/content/cals/repo-items/titles-literary-format

As you'll see, there's some weird values (e.g., "n") in some of the records that i can't really account for, so i'm going to review / address over the weekend and will likely move the parser up to Prod when finished.

**Comment by davekisly** [comment]
@Arty-chan - i noticed there were many records (on DEV, at least) already tagged (esp. w/ Fiction). 

Does this mean that you / Coop staff had populated these records or were they tagged some other way? I'm asking because the view i've set up should be used cautiously in that the majority of records do not appear to contain valid 006 or 008 values that can be mapped to Literary Format. So, if you were to run the parser (on the Lit Format field) against all the records, you would end up w most of those records stripped of their current values. I would advise, then, to filter out the currently populated records via the search filters.

I could re-jig the parser up to skip over records that already contain valid lit format values, but this would require some work and it would be a lone exception to how other fields are handled. So, i'd only do this if strongly preferred and the search filters didn't suffice.

That all noted, i've refined the parser to ignore non-allowable values, which should address the "n" type errors noted above. I've updated DEV: please test again and if it looks good, i can move the updated parser to PROD tomorrow or during the week.

**Comment by Arty-chan** [comment]
You will get some invalid characters if the records that are being coded as audio material rather than books, but there is no overlap, so any character that does not map to a literary format, I would just toss and let the system set it to the default of "None".

At some point, the default value for Literary Format was "Fiction" when the repo-item was created. That was fixed at some point so that the default value was "None".

So, using the view you provided, I will probably just edit it a bit to order by date and re-parse all older records that were set to Fiction by default.

Once the literary format piece has been updated I'll take care of how/what to re-parse.

**Comment by davekisly** [comment]
hi @Arty-chan - re. '_so any character that does not map to a literary format, I would just toss and let the system set it to the default of "None"_...', that's exactly how the lit-format parser should be working now. Can you re-test (on DEV) and if you're good w/ the results, i'll move this up to PROD along w/ the URL parsing updates.

**Comment by Arty-chan** [comment]
it looks like valid values are not setting the format at all. If you check the examples I listed, they all say "None" now.

**Comment by davekisly** [comment]
Let's look at the 006 and 008 tags from first one u list above (https://dev.nnels.ca/items/politics-rights-lawyers-public-policy-and-political-change):

`<marc:controlfield tag="006">m        h      e </marc:controlfield><marc:controlfield tag="008">080604s2007    bccuun  s         0 eng  </marc:controlfield>`

The 006/16 seems to be blank, likewise the 008/33 ... or am i misunderstanding or miscounting the characters?

**Comment by Arty-chan** [comment]
as noted, 006 for that one is coded essay, which is the e near the end, in 008 it's coded as non-fiction which is the 0 before eng

**Comment by davekisly** [comment]
Ah yes, doh. That's me miscounting (by treating the first character as 1, not 0). 

5 minutes and i'll have the updated code in place.

**Comment by Arty-chan** [comment]
thanks, looks good

**Comment by davekisly** [comment]
Ok, i've pulled the latest parser(s) + the new views up to PROD: 
- https://nnels.ca/admin/content/cals/repo-items/source-urls
- https://nnels.ca/admin/content/cals/repo-items/titles-literary-format

**Comment by Arty-chan** [comment]
thanks. re-parse done as well
