### ISSUE TITLE
Parser: Language

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#114]
I know that the parser is pulling from 041$a right now, but I don't think it's using 008 as a fallback.

041		$ad
if no 041, use 008/35-37

**Comment by davekisly** [comment]
Implemented on DEV, some cursory testing. Please test and provide feedback. Here's a new view that provides a starting point: https://dev.nnels.ca/admin/content/cals/repo-items/iso-languages?keys=&field_xml_string_value_op=not&field_xml_string_value=marc%3Adatafield+tag%3D%22041%22&field_access_restrictions_value=All&field_record_set_nid=All&field_title_alternate_value_op=longerthan&field_title_alternate_value=&status=1&field_iso_language_value_op=or&field_iso_language_value=All&sort_by=title&sort_order=ASC&items_per_page=50

Notice the "does not contain" operator in the MARC XML search field. This may help filter out items that don't contain 041 tags.

**Comment by davekisly** [comment]
Question: is there any chance that the 041 and 008 values do not overlap (e.g., eng in one, fre in the other)? I'm asking b/c the field itself accepts multiple values, so does it make sense to test / compare the two fields to determine if there's more than a single language across the two marc tags? (Should the likelihood be v. low, its more efficient to **not** check.)

**Comment by Arty-chan** [comment]
the value in 041 will always have the value in 008, though 041 is where you may have multiple values, since 041$a and 041$d are both repeatable

however, we need the 008 as "fallback" because most of the time 041 is not coded unless multiple languages apply

008 part of the parsing is working, but now it doesn't seem to parse 041 at all...?
examples:
* ita (italian): https://dev.nnels.ca/items/b-betsy
* swe (swedish), iro (iroquais): https://dev.nnels.ca/items/1-suspect-novel

**Comment by davekisly** [comment]
oops, i see what's happened. Will re-commit in 5.

**Comment by davekisly** [comment]
Ok, committed slight revision that should re-implement the 041 parsing.

**Comment by Arty-chan** [comment]
thanks, looks good now

**Comment by davekisly** [comment]
Pulled to Prod. Here's the corresponding view, as well: https://nnels.ca/admin/content/cals/repo-items/iso-languages

**Comment by Arty-chan** [comment]
looks good. 

Note: done re-parse
