### ISSUE TITLE
Parser: Edition (from Original Version/Source)

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#115]
Sorry, I had forgotten this one. Please do this one ahead of language:

pull "as is" from 534$b into DC Relation .IsVersionOf ; same as edition statement (250$a)

Note to self: will need to reparse "DC relations" for all Crane titles but make sure to re-add collection DC relations.

**Comment by davekisly** [comment]
Implemented this on DEV, but have not tested thoroughly. Please test and provide feedback. 

This might be a good place to start: https://dev.nnels.ca/admin/content/cals/repo-items/titles-alternate-uniform?keys=&field_xml_string_value_op=contains&field_xml_string_value=marc%3Adatafield+tag%3D%22534%22&field_access_restrictions_value=All&field_record_set_nid=All&field_title_alternate_value_op=longerthan&field_title_alternate_value=&status=All&sort_by=title&sort_order=ASC&items_per_page=50

**Comment by Arty-chan** [comment]
thanks, this seems to work fine

**Comment by davekisly** [comment]
Pulled to Prod. Here's the Prod version of the view above: https://nnels.ca/admin/content/cals/repo-items/titles-alternate-uniform?keys=&field_xml_string_value_op=contains&field_xml_string_value=marc%3Adatafield+tag%3D%22534%22&field_access_restrictions_value=All&field_record_set_nid=All&field_title_alternate_value_op=longerthan&field_title_alternate_value=&status=All&sort_by=title&sort_order=ASC&items_per_page=50

**Comment by Arty-chan** [comment]
reparsed Crane set as well
