### ISSUE TITLE
Parser: Contributor

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#116]
For 700, $a is currently mapped to Contributor.

I would like to change this so that if 
* 700$e is "author" or
* 700$4 is "aut"
then 700$a gets maps to Creator instead.

Note: $e or $4 should be exact but may have trailing punctuation.

Still goes through same normalization process.

**Comment by davekisly** [comment]
Ok, i've got this working on my local, but have a couple questions:
- are there cases where a MARC record might have creator values both in the original 100 fields (e.g.,100$a, 110$a|$b, 111$a) currently used and then also in the 700 fields described above?
- If yes, do they need to be parsed in a specific order?

The reason for asking is the way the parser is set up, it automatically parses dc_contributor before dc_creator (simply an alphabetical operation in the way the field mappings are pulled). This effectively means that 700 values would be added to the Creator array before values from the 100s, which in turn will be reflected in the public display.

If we need to prioritize 100 series fields above 700 ones, then i have do to a little re-arranging. But, if its highly unlikely to have creator values in both field groups (1xx, 7xx), then i'll leave as is.

**Comment by Arty-chan** [comment]
we will need to rearrange. 100 definitely takes priority over 700; 100 series will only ever have 1 entry so there's no order inside of that. While 700 may have multiple entries the order inside of 700 series does not matter.

**Comment by davekisly** [comment]
@Arty-chan, i've just pushed refinements to the creator and contributor parsers to accommodate the 700$e and 700$4 qualifiers above. Please test and let me know if this works.

I didn't find many records to test with, so I modified this one by sticking my own name into the 100 field: https://dev.nnels.ca/items/country-nourished-self-doubt-documents-post-confederation-canadian-history

**Comment by Arty-chan** [comment]
new addition looks good.

though I just noticed that the normalizer strips periods even if creator/contributor ends with initial:
Example: Scheingold, Stuart A.
In 100$a: https://dev.nnels.ca/node/63268/

I thought we had resolved this previously...?

Note to self: will want to change creator to semicolon separator; add contributor to title display

**Comment by davekisly** [comment]
I do believe authors / contributors are fed thru a check for abbreviations at the end of the string. Will review this later.

**Comment by davekisly** [comment]
I'm not certain why it stopped working, but i did end up refining the abbreviation check a bit to allow for trailing abbreviations of up to three letters (e.g., "blah blah blah edn." will be treated as an abbreviation whereas "blah blah blah blah ednn." should be stripped of its trailing period). I'm sure we'll continue to return some false positives (its difficult to account for all patterns), but the stop-word manager should hopefully give us a quick way to address some of the recurring patterns that don't otherwise fit into the abbreviation parsing. Please test the node above again and let me know if that resolves the issue?

**Comment by Arty-chan** [comment]
looks good, thanks!

**Comment by Arty-chan** [comment]
was this pushed to prod?

**Comment by davekisly** [comment]
Not sure, tbh. If you're good w/ the parser vis-a-vis some of the other tickets, i can pull the latest version to Prod tonight or tomorrow AM. 

in line w/ earlier protocols / division of labor re. who should operate directly on Prod, i generally defer to JS to manage updates on the live server, exceptions being when i'm asked and/or in cases where i assume i'll get to critical security update on wed am before people on your end (west coast). 

In any case, as above, i'll update Prod if you're good w/ the current parser going up, but perhaps we should also schedule a discussion at some point to revisit the general policies?

**Comment by Arty-chan** [comment]
Since this is done, I'll close for now with the assumption that it'll be pushed to prod when #121 is done.
