### ISSUE TITLE
Parser: Audience

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#117]
Check for 006/05, otherwise, pull from 008/22

Mapping should not have to change in terms of which field is set for Audience in Drupal, since the parser was already dealing with 008, but for reference:
a - Preschool
b - Primary
c - Pre-adolescent
d - Adolescent
e - Adult
f - Specialized
g - General
j - Juvenile
Anything else should just not set Audience

If you need any clarification, please let me know.

**Comment by davekisly** [comment]
I've just committed to DEV a new parser "_cals_importer_get_audience_from_marc" to pull from 006 (with 008 as the fallback). Please test when you have a chance.

**Comment by Arty-chan** [comment]
tested with a bunch of the codes using a combination of 008 alone and with 006 sometimes matching sometimes not.

Can we actually remove the | and u from the mapping? Right now they map to "No attempt to code" and "Unknown" respectively, and I just don't see them as being useful.

**Comment by davekisly** [comment]
Can you toss me 1-2 examples of records that don't seem to match properly?

And yes, no problem - i've just pulled the "no attempt to code" and "unknown" values from that field.

**Comment by Arty-chan** [comment]
sorry if that wasn't clear. that was a note more to myself that I purposely tested using values where the 006 and 008 didn't match in a couple of cases.

Everything looks good now that we've removed those two values. We should remove those two values from the Drupal field as well, but not a big deal.

Did you want to push to PROD or wait for other changes?

**Comment by davekisly** [comment]
ok cool. I'll pull this up to Prod later tonight. 

And yes, actually i did pull the values from the Drupal field; the parser does a live look-up against Drupal's field definitions to determine the allowable values. I will need to repeat this on Prod, as well, which i'll do when i pull the latest parser up.

**Comment by davekisly** [comment]
Just confirming that i've pulled the latest up to PROD, so you should be good to re-parse Audience there, as well. 

I ended up setting up a view to delete some of the records that included the "unknown" values (before i could delete them from the Drupal field definition), so you can also use this to re-populate the audience field as required: https://nnels.ca/admin/content/cals/repo-items/audience

**Comment by Arty-chan** [comment]
reparse of Audience is done on PROD
