### ISSUE TITLE
Parser: Table of Contents

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#121]
As discussed,

505$agrt in the order of whatever is in the MARC record brought in "as is" (no clean up/punctuation stripping necessary) into a new (filtered HTML) text area field that we can call "Contents".

To help with readability, all double hyphens ( -- ) should be replaced with `<br>` 

Will be displayed below Summary/Abstract on Title details page.

**Comment by davekisly** [comment]
@Arty-chan - i've added a parser on the TOC (505$agrt) field, now committed to DEV. You can see an example of a parsed record here: https://dev.nnels.ca/items/god-wills-it-understanding-crusades

As you'll see, i updated the view to include this new field. In place of <br> delimiters, i ended up wrapping all the double hypenated fields into <li> tags as they might allow for improved theming (vs. simpler <br>'s).

As a side-point, i've also added a new admin view here: https://dev.nnels.ca/admin/content/cals/repo-items/marcxml-output

If you follow the example, the xml string column should include the xml for the tag you add, e.g.,: https://dev.nnels.ca/admin/content/cals/repo-items/marcxml-output?field_keyword_index_value=&field_xml_string_value_1=marc%3Adatafield+tag%3D%22505%22&items_per_page=40

Hopefully, this can give you a snap-shot of what content / values are likely to be teased out when you re-parse the field.

**Comment by Arty-chan** [comment]
great, thanks! 

Good idea on the wrapper. The only comment I have at the moment is that if all the items are wrapped in <li> then the first one should be too, but not sure how you'd go about that...

**Comment by davekisly** [comment]
That's actually easier to implement than what i ended up doing. I just assumed the first item was some sort of heading for the items that followed. So, no worries, i'll amend the code a bit later today to address that.

**Comment by davekisly** [comment]
@Arty-chan - should have asked this before, but is this new Contents field potentially multi-valued? 

For example, if a given 505 includes 3 of the subfields you indicated (a, g, r or t), would that result in 3 discrete "Contents" entries? 

Or, would we concatenate all into a single entry?

**Comment by davekisly** [comment]
Second question: should we add this field to the search index? In the few records i've looked at, the content seems fairly rich / relevant.

**Comment by Arty-chan** [comment]
all subfields would go into the same "Contents" drupal field (so no multi-value), because the subfields usually indicate different parts of the Contents (e.g. chapter title / author; module number / module title).

Yes, contents should be indexed, though treated on the lower side of relevant scale.

**Comment by davekisly** [comment]
Have a look at this record to see if the Contents parsing is working as expected: https://dev.nnels.ca/items/god-wills-it-understanding-crusades

As you'll see, i've added a subfield $g to the 505 tag (starting with "Subfield Code G!!!"). Both subfields ($a and $g) are pulled into one single list. That do the trick?

**Comment by Arty-chan** [comment]
is the code wrapping each subfield in a list item as well? 
I edited the record so that the subfield g is on its own after the previous subfield a, and it ended up in its own list item, but I expected it to be appended to the one before.

I would expect everything to be concatenated and then split into list items at the double hyphen.
For example: 
"$gNr. 1.$tRegion Neusiedlersee --$gNr. 2.$tRegion Rosalia/Lithagebirge" turns into:
item 1: Nr. 1. Region Neusiedlersee
item 2: Nr. 2. Region Rosalia/Lithagebirge

Another example:
$tChurch members, 1816-1831 --$tHistory of the Second Presbyterian Church of West Durham /$rby L. H. Fellows
item 1: Church members, 1816-1831
item 2: History of the Second Presbyterian Church of West Durham / by L. H. Fellows

**Comment by davekisly** [comment]
As the parser works now, everything will (should) be concatenated into a single list comprised of one `<ul>` (list) and multiple `<li>`'s (list items). I think its what you are describing above, but to clarify, here's a snapshot of the record above viewed in "plain text" mode (so we can look at the actual HTML):

![screen shot 2016-07-12 at 3 04 17 pm](https://cloud.githubusercontent.com/assets/852550/16779852/fe32738a-4841-11e6-9723-5bf6f3a522e4.png)

Am i misunderstanding what your preference is? Were you thinking each discrete subfield would go into its own UL? I can do either, just let me know.

**Comment by Arty-chan** [comment]
one UL and multiple LI is correct, however, how does the code determine where a LI begins and where it ends?

The way it should work is that LI are split at the double hyphen regardless of subfield. So, using the examples above:

```
$gNr. 1.$tRegion Neusiedlersee --$gNr. 2.$tRegion Rosalia/Lithagebirge
should turn into:
<ul>
  <li>Nr. 1. Region Neusiedlersee</li>
  <li>Nr. 2. Region Rosalia/Lithagebirge</li>
</ul>

$tChurch members, 1816-1831 --$tHistory of the Second Presbyterian Church of West Durham /$rby L. H. Fellows
should turn into:
<ul>
  <li>Church members, 1816-1831</li>
  <li>History of the Second Presbyterian Church of West Durham / by L. H. Fellows</li>
</ul>
```
Notice that in the first example, each list item actually comprises of two subfields. In the second example, the second list item also comprises of two (different) subfields.

**Comment by davekisly** [comment]
The way the code works now reflects my interpretation of your earlier comment "then the first one should be too", i.e., that the first item in the subfield (which is not hyphenated) should go into its own discrete field.

Heading out now, let's skype on this? I can touch base at 2pm your time - today or tomorrow? Or anytime on Thurs?

**Comment by Arty-chan** [comment]
that comment reflects the fact that in the previous implementation, the first item was not in the list at all.

sure 2pm today works.

**Comment by Arty-chan** [comment]
has this been updated since we chatted? just want to know if more testing needs to be done

**Comment by davekisly** [comment]
Sorry, pulled into other things last week. Not much left on this, should have an update for you to test by this time tomorrow.

**Comment by davekisly** [comment]
Sorry @Arty-chan - i've pushed an update to DEV (as of 2 days ago), but must have neglected to press "comment" on the reply i had drafted. Doh! Please test when you have a chance, maybe starting w/ the Crusades example mentioned above: https://dev.nnels.ca/items/god-wills-it-understanding-crusades

**Comment by Arty-chan** [comment]
tested a few records with different formatting.

Looks good.

Please add the Contents field to PROD as you push up the parser. Please also add it to the title view display underneath summary as on dev (with the setting to hide label if empty).

Note to self: will need to re-parse for Contents.

**Comment by davekisly** [comment]
hi @Arty-chan - i've just: 
- pulled the latest version of the importer to PROD
- added the contents field to Prod
- added an "xml output" view here: https://nnels.ca/admin/content/cals/repo-items/marcxml-output
- also see: https://nnels.ca/admin/content/cals/repo-items/marcxml-output?field_keyword_index_value=&field_xml_string_value_1=marc%3Adatafield%20tag%3D%22505%22&items_per_page=40
- test parsed the first item (Crusades) on the list above: https://nnels.ca/items/god-wills-it-understanding-crusades
- as you'll see from the above, i've also added Contents to the detail view.

The parser should address the various updates to other tickets, as well. Please test.

**Comment by Arty-chan** [comment]
When I ran this, it gave this error at the end of the list of titles it processed, and still seemed to process okay:
> An error occurred while processing views_bulk_operations_active_queue_process with arguments: views_bulk_operations_active_queue_process
> repository_items_marcxml_output modified by: cals_importer_views_post_execute

**Comment by davekisly** [comment]
This seems a somewhat recurring problem that is sometimes associated w/ server issues (e.g., cron running, indexing running) and once or twice (i believe) with values being truncated due to the size of the content being parsed. I might suggest you run this in smaller batches. If it fails then, perhaps we can narrow it down to one or more specific records. And if that doesn't seem the issue, i'll dig in to review further.

**Comment by Arty-chan** [comment]
the parsing itself worked fine, just wasn't sure if the error was a problem.

Will report on results in a bit

**Comment by Arty-chan** [comment]
everything looks good, reparsed on PROD. Closing ticket!
