### ISSUE TITLE
Field Collection/Attachment Delete button has disappeared

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#126]
Not sure when this happened, but must be fairly recently.

I no longer see the option to delete the file attachment. Nor can I do it once I'm in the edit screen.

![screenshot 02](https://cloud.githubusercontent.com/assets/1790326/17762406/3270177a-64c5-11e6-981b-ff6204700822.jpg)

**Comment by davekisly** [comment]
For some reason, "delete" was turned off in the field collection view. I've turned it back on. Is difficult to track changes in views (unless we turn on something like views revisions, https://www.drupal.org/project/views_revisions) so i have no idea as to why that might be.

**Comment by Arty-chan** [comment]
noted, thanks
