### ISSUE TITLE
Publisher and Publisher Source: post import updates

### ISSUE THREAD

**Issue by davekisly** [BCLibCoop/nnels#127]
Summarizing a couple skype and email conversations w/ Farrah, the BC Coop requests the addition of a new Action Script for the purpose of updating the Publisher and Publisher Source values. Integrated into the integrated into the MARC xml record-set interface, this script will allow staff to:

1. copy current **Publisher** values into **Publisher Source**
2. Replace the current **Publisher** values with a limited number of replacements selected at run-time (ideally from a drop-down field or similar). The replacements will include values such as "Vancouver, BC: BC Libraries Cooperative" and "Vancouver, BC: UBC Crane Library" (among a possible handful of others still to be identified).

In order to simplify the process and minimize the potential for keystroke mistakes, we will create a new taxonomy field "Publishers" to populate the drop-down values in the drop-down field mentioned in point 2 above.  (This taxonomy field could, in the future, potentially replace the current open-ended text field used for Publisher, but that's beyond the scope of this ticket.)

**Comment by davekisly** [comment]
hi Farrah, i've added a first version of the publisher / publisher source update script to DEV. You can see this by selecting one of the existing record-sets (https://dev.nnels.ca/admin/content/cals/records-sets) and then selecting "5. Update Publisher and Publisher Source". 

Might still be a bit raw around the edges, so please test w/ a couple records (or sets) and report back if you see any issues!

**Comment by flittle8** [comment]
Thanks Dave, I've tested this with a few record sets and I haven't come across any issues. Looks like it does exactly what we need it to.

**Comment by flittle8** [comment]
Also, for the foreseeable future, we only need those 2 publishers in the drop-down.
