### ISSUE TITLE
Leader

### ISSUE THREAD

**Issue by flittle8** [BCLibCoop/nnels#133]
The codes for character positions 09 and 17 need to be updated:

- 09 (character encoding scheme) = blank
- 17 (encoding level) = 2

**Comment by davekisly** [comment]
I've updated the leader export code on position 17. It should now default to "2". As an example, the current leader value for https://dev.nnels.ca/items/1-dead-attic-after-katrina is 
- "10000nim 22XXXXX7u 4500" (no quotes in the actual export).

Is this correct?

As far as i can tell, position 09 was already pumping out a blank character, but please advise if not the case.

**Comment by flittle8** [comment]
Hi Dave, the leader doesn't look like it's being generated correctly. There should be 24 character positions (I've copied the positions & their data below). 
In the example above there are only 22 positions and many of the codes are incorrect; for example: 06 should be 'a' ('i' is for MP3s); 09 should be blank (not '2'); 11 should be '2' (not 'X'); 12-16 should be 'base address of data' (system-generated); 17 should be '2' (not 'u'); 18 should be 'u' (not blank); 19 should be blank (not '4') and 20-23 should be 4500.

***
All 24 character positions (00-23) are mandatory.

00-04 (record length) = entry is system generated (count the entire length of the bibliographic record)
05 (record status) = default code n 
06 (type of record) = generate the code based on the file format in Drupal: 
MP3 = i 
all other file formats = a 
07 (bibliographic level) = default code m
08 (type of control) = default code blank
09 (character encoding scheme) = default code blank
10 (indicator count) = default code 2
11 (subfield code count) = default code 2
12-16 (base address of data) = always system generated...
17 (encoding level) = default code 2
18 (descriptive cataloguing form) = default code u
19 (multipart resource record level) = default code blank
20-23 (entry map) = default codes: 20=4, 21=5, 22=0, 23=0

**Comment by davekisly** [comment]
hi Farrah, I should have mentioned i've got a couple placeholders, e.g., 00-04 ... i hardcoded 1000 and 12-16 i hardcoded XXXX. And, the value for 06 is something I believe Jonathan will need to determine. 

For added reference, you can see my code and inline comments starting here: https://github.com/BCLibCoop/nnels-drupal-modules-cals_importer/blob/master/cals_importer.exporter_callbacks.inc#L49

This reminds me, this should actually be managed as file management export, so eventually this will end up in Jonathan's camp. I'll try to address the 00-04 and 12-16 stuff first, tho.

**Comment by davekisly** [comment]
Based on today's meeting, JS will review the MARC File library to determine how the LEADER field is generated.

**Comment by gitschatz** [comment]
### File_MARC_Record class:
_Constructor_ - initialises a 24-byte whitespace string
_setLeaderLengths($record_length, $base_address)_ lines 287-321
		Sets record length in the leader
		Called by File_MARC_Record::toRaw()

_private	_buildDirectory()_
		Ensures leader == LEADER_LEN constant (24)
		Ensures directory == DIRECTORY_ENTRY_LEN (12)
		Sets $base_address for MARC::RECORD:USMARC rules
		Called by File_MARC_Record::toRaw()

_toXML()_ 
                may set record status and type (bytes 5, 6) to defaults if they are empty

### File_MARC class
_private _decode()_
	stores record legnth
	checks directory entries length, leader length and bytes 12-16 offset

_File_MARC_Record::toRaw()_
	not calleddirectly in library, the field classes have their own toRaw() method that's used by the Linter as part of the checkRecord() routine.

**Comment by gitschatz** [comment]
## Strategy

**For each file entity:**
- Use + operator to merge stub and snippet, preserving our tag keys
- Sort by keys, except LDR
- Use sorted array to build File_MARC_Record object
- Lint it
- If it's good, call its method ::toRaw()* and append to a temp variable, $records 
- When bulk operation reaches end of context, instantiate a File_MARCXML object with the raw $records as SOURCE_STRING
- Dump XML to file and serve

*this should set the record length and base address for us_

**Comment by gitschatz** [comment]
@flittle8 
I've a test build on dev ready for checking the leader generation as well as the final records in collections. 

Variable bytes in leader: 
I'm calculating record length as well as base address for each newly merged record. Let me know if you need a walkthrough of those.

Please test with this view: https://dev.nnels.ca/admin/content/cals/repo-items/searchable-marc-xml-file-builder

The only requirement for export is that the records have been parsed (have MARC XML string), they will be skipped if not. Record stubs will be generated if not existing and file resource snippets will be always be (re)-generated each time to account for updates.

**Comment by flittle8** [comment]
Great, thanks! I'll do some testing over the next week.

**Comment by flittle8** [comment]
@gitschatz 
I started to test our exported MARC records and I think something's awry, so I'll wait to hear back from you before I continue testing further. 

An example is [node/7062](https://dev.nnels.ca/node/7063/) ([exported record viewable here](https://dev.nnels.ca/sites/default/files/marc_exports/marcxml_export_65936.xml)).

The issue is that the **Leader field** is only composed of digits: `<leader>0135700349224500</leader>`
You can see further up in this github string how the leader is to be composed (includes letters & digits)

I checked a few other files and the leader displays the same way - as a string of digits.

**Comment by gitschatz** [comment]
@flittle8 Part of this was due to the version mismatch from my local and dev. I've brought them to parity and leaders are alpha-numeric once again: https://dev.nnels.ca/sites/default/files/marc_exports/marcxml_export_65958.xml

I am still seeing some odd formatting in other records though, will continue to review this feature.

**Comment by flittle8** [comment]
@gitschatz Thanks for bringing those bits together. It definitely looks better, but there are a couple things that I've noticed, maybe you noticed already too:

- position 06: MP3s should be **i**, while all other formats **a** (everything seems to default to **a**)
https://dev.nnels.ca/sites/default/files/marc_exports/marcxml_export_65962.xml 
- position 11: default should be **2** (seems to default to **0**)

**Comment by gitschatz** [comment]
@flittle8 
I believe I've squashed these discrepancies: the positions were getting knocked back in certain situations and byte 6 was getting lost in a bad merge.

Recent run of those mp3 resources for your consideration: https://dev.nnels.ca/sites/default/files/marc_exports/marcxml_export_66023.xml

leader length and base address are also properly zero-padded as well.

One thing to note (it keeps bugging me) is that there a double blank space for positions 9 and 10 but the browser will only render one in XML source view. The record we serve actually has two. You confirm by viewing the raw source in-browser and pasting into text editor.

**Comment by flittle8** [comment]
Thanks Jonathan. I think you mean there should be a double blank space for positions 8 and 9?
If so, that's perfect, then the only thing that needs updating is **position 17**, the encoding level, which should default to **u**. Then we can call this done for good :)

**Comment by gitschatz** [comment]
Alright set to u - Unknown by default.

**Comment by flittle8** [comment]
Great, thanks. The leader looks good to me now, so I'll close this ticket!
