### ISSUE TITLE
Review dates in NNELS - Issued, Copyrighted, Created

### ISSUE THREAD

**Issue by davekisly** [BCLibCoop/nnels#143]
Per the discussion in https://github.com/BCLibCoop/nnels/issues/136 let's review whether we can streamline the dates in the parent node - i.e., can we collapse Date Issued and Date Copyrighted into a single field (Copyrighted)? 

Will create a View (with various filters) to pull back a list of nodes so we can quickly eyeball the feasibility of collapsing Issued and Copyrighted.

**Comment by flittle8** [comment]
Hi Dave, I'm going to close this as I think we decided to use Date issued. Let me know if I need to reopen this.
