### ISSUE TITLE
Include Terms file in all .zips

### ISSUE THREAD

**Issue by sleslie** [BCLibCoop/nnels#20]
Ideally we should have, in every zip that is downloaded from the system, a file named terms-conditions.txt with the following text:

"You shall use this content for personal, non-commercial use and you may only copy, transfer and burn the content for such use. Content shall not be modified, copied, distributed, repackaged, transmitted, sold or otherwise used in a manner inconsistent with the rights of copyright owners.

Vous pouvez utiliser le contenu seulement à des fins personnelles et non commerciales, et ne pouvez le copier, le transférer ou le graver qu'à de telles fins. Le contenu ne doit pas être modifié, copié, distribué, réorganisé, transmis, vendu ou utilisé autrement, d'une manière incompatible avec les droits des détenteurs des droits d'auteur."

This is a legal CYA move. For content going forward, we should probably just include this as part of our production workflow. For legacy content (all zips in ceph) we need to insert this file into the existing zips. I know this is doable via shell script (though not sure how to deal with ceph file system in such a script) but there may be other ideas on how to do it. Suggestions?

**Comment by Arty-chan** [comment]
@kpjorgen as discussed, please check with Ben

**Comment by kpjorgen** [comment]
Project is being done by coop SysOps team. Closing.
