### ISSUE TITLE
French translations for NNELS breadcrumbs

### ISSUE THREAD

**Issue by kpjorgen** [BCLibCoop/nnels#61]
Some of the breadcrumbs need to be translated. For example, ‘Home/Hinton Municipal Library’ on https://nnels.ca/organizations/hinton-municipal-library. I included this in the translation package for @mbehiels.

Thanks,
kris

**Comment by Arty-chan** [comment]
@kpjorgen please check if resolved

**Comment by kpjorgen** [comment]
Everything is fine. Closing.
