### ISSUE TITLE
Label Issues & Missing French Translations in Repo Items View

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#81]
In follow up to #80 , some labels are inconsistent and some French labels are missing from the repo item view. 

@kpjorgen if we have "official" translations for these, could you please put them in this thread? (I could've sworn these were translated and completed a while ago)

Download (format filesize) => Télécharger (format filesize)
Login to access (format filesize) => Connectez à l'accès (format filesize)

Language(s) => Langue(s)

Under Date
Issued => Émis (is what is shown on the admin side)
Created => Crée
Copyrighted => Droit d'auteur

Not sure when "Performed/Narrated by" was shortened to one word, which is fine, but then it should be "Narrator"
"Narrator" => "Narrateur"
And the logged in version should be the same so that it's consistent.

On a slight tangent, the "Login", "Log Out", and "Sign Up" buttons are still in English. (should be "Connexion", "Déconnexion", "S'incrirez")

**Comment by Arty-chan** [comment]
@kpjorgen please look over that all of these issues were resolved

**Comment by kpjorgen** [comment]
Closing -- only issue is the CAPTCHA. Will deal with separately.
