### ISSUE TITLE
Audit trail timestamp changes all timestamps

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#95]
As mentioned in #85 

 when re-parsing a record, the audit trail changes the timestamp for all instances instead of only applying it to the newest instances of "Parse" and "Normalize" e.g. https://staging.nnels.ca/admin/content/cals/records-sets/test-set

**Comment by kpjorgen** [comment]
As discussed in Skype, will wait for a patch. Dave will contact whoever takes care of the patch.
