### ISSUE TITLE
Access Rights

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#96]
Access Rights used to show on:

field collection view repo files (Field collection item) : Embed - Detail - Admin

it's an easy fix, so I can do it, but will wait until #85 is done. Just wanted to note it here

Notes:
* use space for separator
* need to add CSS class: .repo-item.available-formats .views-field views-field-field-access-rights to the same ruleset as: .repo-item.available-formats .views-field-field-performer

**Comment by Arty-chan** [comment]
ha, I said I could maybe do it, but I can't seem to figure out how we would only display it once, instead of multiple times.

We need to display access rights. This is really for staff roles. I'd like to add it at the bottom of the available formats area, but maybe it would be simple to add it as a separate block/embed?

**Comment by davekisly** [comment]
hi @Arty-chan - just so i'm clear, is Access Rights the text entry you see under the "Rights / Permissions" tab when you're editing a repo item node, or is it the radio button field "Access Restrictions" right above it? Or, a different field altogether?

<img width="951" alt="screen shot 2015-11-30 at 8 25 38 pm" src="https://cloud.githubusercontent.com/assets/852550/11489838/df9c4f56-97a0-11e5-89c1-383cfe1f841d.png">

**Comment by Arty-chan** [comment]
the text string based one called "Access Rights" as you see in the screenshot

**Comment by davekisly** [comment]
Ok, have a look here and let me know which one (if either) works for you: https://dev.nnels.ca/items/king-and-kanata-canadian-indians-and-first-world-war

- option 1: a side block titled "Access Rights". This is potentially less accessible (should u have admins accessing the site w/ assistive devices) vs ...
- option 2: Access Rights is embedded in the main "Details" view, lodged at the top of the field list. 
<img width="933" alt="screen shot 2015-12-01 at 6 09 42 pm" src="https://cloud.githubusercontent.com/assets/852550/11517413/5225b786-9857-11e5-96cf-6ea4461024af.png">

- both options are visible only to Contributors and other "admin" roles.

Preference(s)? Thoughts?

**Comment by Arty-chan** [comment]
side block might actually work better. It probably stands out more being in the side block. I also appreciate the record set information for admin/site manager.

**Comment by davekisly** [comment]
have a look at https://nnels.ca/items/crazy-mans-creek - i've pulled over both the Access Rights and the Parent Record Set blocks up to Prod.

If the two are visible to the same roles (more or less), i can fold these into a single view/block which might make things a bit tidier and efficient. We could add other "admin-only" fields into this block as well, if that helps in your day to day management of these records. Just let me know, your call.

**Comment by Arty-chan** [comment]
looks good. thanks for taking a look at this since I hadn't even thought about using the sidebar...

updated the roles as necessary. Roles are different for the two blocks, so let's leave as is. thanks again.
