### ISSUE TITLE
Errors while Parsing MARC

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#97]
I know that we've encountered this sort of thing before, but not sure if it was just a simple reset of a cache or similar or something more complex.

Was trying to parse this set: https://nnels.ca/admin/content/cals/records-sets/governor-generals-awards-2015

Error received:
> An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: /batch?id=14128&op=do StatusText: Internal Server Error ResponseText: 

Error message when back on MARC record set page:
> An error occurred while processing views_bulk_operations_active_queue_process with arguments: views_bulk_operations_active_queue_process

I suspect it's hitting up against something in the titles that are currently not yet fully parsed:
* La Fabrica
* Solomon Gursky
* Twenty-one Cardinals
* Daddy Lenin and other stories

Unfortunately, I don't see what they have in common.

I did notice that the parser now seems to make empty system control number fields in many cases. You'll notice some of them have a comma in the system number control column, delineating multiple values, but they're blank values. Not sure if that's related or not.

**Comment by davekisly** [comment]
I'll reproduce this on DEV and test there over the weekend.

**Comment by Arty-chan** [comment]
@davekisly Did you re-parse the existing records on PROD? If so, please do not do this on PROD except for the 4 titles I listed that did not properly parse. We are currently producing these titles and making changes to the repo-item information which has been overwritten due to the re-parse.

**Comment by davekisly** [comment]
Yes, i did quickly run the parser to see if i could reproduce the issue. Won't touch on prod going forward or until further notice.

**Comment by davekisly** [comment]
hi @Arty-chan - please run the parser here on DEV and let me know if its working as expected? 

https://dev.nnels.ca/admin/content/cals/records-sets/governor-generals-awards-2015

I found a couple minor bugs, which i cleaned up. Also discovered that the VBO can choke on otherwise benign PHP, so i commented out some of that. It now seems to run thru all 34 items, but please test and confirm. I can pull to Production later today if it looks good.

**Comment by Arty-chan** [comment]
well, as you say, it parses correctly. Can you tell me whether it's likely to affect how things are parsed? I didn't check the results in detail since the records vary quite a bit in terms of what information is in there.

If there's nothing in particular, then I think we can go ahead with the minor update to staging and prod

**Comment by davekisly** [comment]
If the updates changed anything, it would be in the field collections. So, if can run a couple spot checks, that's where i'd look first.

**Comment by Arty-chan** [comment]
Checked a couple of them and they look okay.

**Comment by davekisly** [comment]
alrightee, i'll pull this up to Prod shortly.

**Comment by davekisly** [comment]
hi Cynthia - i've pulled the updates to Prod, and ran a quick test against a single record "La Fabrica" (which seemed to parse w/out error). Please test w/ any of the other remaining entries.

**Comment by Arty-chan** [comment]
unfortunately, I've made substantial changes to all the records in this set. Since they parsed on dev, I'll just close this for now. Thanks for fixing.

**Comment by Arty-chan** [comment]
okay, decided to make a test set on prod to see what would happen and it would not generate the stubs.

Set: https://nnels.ca/admin/content/cals/records-sets/test-gg-set

> An AJAX HTTP error occurred. HTTP Result Code: 500 Debugging information follows. Path: /batch?id=14203&op=do StatusText: Internal Server Error ResponseText:

> Finished with an error.

If you look at the results, it seems to have created 1 stub then encountered the error.

Feel free to parse/edit any records in this test set.

**Comment by davekisly** [comment]
Hmm, interesting. The module does populate the records fine and parses both on DEV and on my local, e.g.: https://dev.nnels.ca/admin/content/cals/records-sets/test

I will review further ... but among other things, i suspect its best to run the parser(s) on PROD at off-peak hours.

**Comment by Arty-chan** [comment]
if it were a large batch I understand, but when we're only trying to parse a few titles, it doesn't make sense to me that peak/off-peak would affect it especially since we're not a heavily used site...

**Comment by davekisly** [comment]
Even a small batch consumes a fair amount of overhead: there's a lot of node_saves(), field collection updates, normalization (etc.). Its not a trivial process and what i've noticed in the past is that the parsing will fail when run concurrently with cron, db backups, search api indexing and the like.

Anyway, i will poke around tomorrow am and report back. I do see a number of warnings associated w/ 533 and 534 "offset" warnings (i think related to some of Jonathan's updates). They shouldn't be fatal but perhaps i can cull some of those and also tweak the memory settings in this module.

**Comment by kpjorgen** [comment]
Had a convo with Dave and looks like everything is functioning properly again.

Thanks all!
