### ISSUE TITLE
Login /Connector Stats Aggregation and Display

### ISSUE THREAD

**Issue by kpjorgen** [BCLibCoop/nnels#98]
Hi Dave,

NNELS Connector metrics data is now accumulating. Next step is to design a place on NNELS.ca where the data can be searched and displayed.

The metics being collected are:

- New users signing up with NNELS, and what site they are registering through
- Returning users, and their associated connector
- Blocked users, and their associated connector
- Blocked users subset:
      - username unknown
      - bad PIN
      - invalid patron type
      - blocked account
- If users are logging in through a referring URL or the NNELS site
- Anonymous users (no login attempt)
      - This type of user is composed of two types:
         - a user who has landed on the site from somewhere else
         - and users who have tried to login unsuccessfully and is presented w/ the login form again.

Ideally, an administrator should be able to go to the Login/Connector Stats area (https://nnels.ca/admin/people/cals/login-stats) and do the following:

- select an organization, and be able to view a detailed report of the activity attached to that specific organization;
- select a province, and be able to view an overview report of the connected organization(s);
      - Within this report, the user should be able to select a specific organization to see a detailed report
- see an overview of the activity nation-wide, categorized by province

The data should be available for monthly and annual reporting.

Reports would come in two types: overview report, and detailed report. The overview report would consist of:

- New user sign-ups
- Returning users
- Blocked users
- Anonymous users

The detailed reports would contain the full range of metrics as listed above.

It would be nice to have an option to build a custom report as well, but can add this in later.

We can discuss this when you have time available.

Thanks,
Kris

**Comment by davekisly** [comment]
hi Kris, notwithstanding issue #77, does this search / report functionality address your requirements?

https://dev.nnels.ca/admin/people/cals/login-stats

**Comment by kpjorgen** [comment]
Hi Dave,

This looks great! Can you get that up on production?

Thanks!
Kris


Kris Jorgensen
Project Coordinator, NNELS
https://nnels.ca
kris.jorgensen@bc.libraries.coop
Toll Free 1-855-383-5761 ext 1034
Cell 778-983-0203

**Comment by davekisly** [comment]
hi Kris, here u go: https://nnels.ca/admin/people/cals/login-stats

**Comment by kpjorgen** [comment]
Hi Dave,

I've been playing around with this and it works great! Thanks for the work here. Closing ticket.
