### ISSUE TITLE
Parsing Title Information

### ISSUE THREAD

**Issue by Arty-chan** [BCLibCoop/nnels#99]
So, apparently one of the crucial pieces of information that was never considered is the edition statement and parts of the title.

## Title
Title should include the following subfields from 245
$a (does this already)
$b (fairly sure it does this already)
$n (does not do this)
$p (does not do this)

Similarly, Alternate Title should pull from 246 if the first indicator is 1 or 3, subfields $abnp

Uniform title should pull from 130 $anp or if 130 does not exist, 240 where first indicator is 1, subfields $anp

We will also need to run a one-time script to populate the repo-item metadata from existing MARCXML.

Let me know if you have any questions.

**Comment by davekisly** [comment]
Sure, that'll be ok, i'll update the marc importer and also set up something similar to the other "one-time" parsers.

Will shoot for next week, but if not then, early Jan ok timing wise?

**Comment by Arty-chan** [comment]
sooner the better, especially if I need to test and/or parse some records over the holiday period; one-time script can definitely wait until early Jan though

**Comment by Arty-chan** [comment]
added info for some changes to title parsing. For the one-time script, possible to only reparse subfields $np and append to title? Mostly because we may have made corrections to the title

alternate and uniform title, we should be able to just do a one-time script in general since I don't think alternate title was being parsed

**Comment by davekisly** [comment]
Questions: 

1. can u provide me or point to record sets that include 245 n and p tags?
2. in records that include 245 fields that include 1+ subfields (e.g., b and/or n and/or p), is there a preferred order to parse these in and a preferred way to concatenate these into a single title?
3. i guess question 2. also applies to Alternate Titles and Uniform Titles.

**Comment by Arty-chan** [comment]
1) there's at least one record with it in the small test set on staging: https://staging.nnels.ca/admin/content/cals/records-sets/test-set
2) As far as I know, OPACs tend to display 245 "as is" simply without the subfield letters, which is why there is so much punctuation in 245. I think we can follow the same practice we have so far, except with $np added.

Based on my understanding of the way it parses right now
i) strip $c and everything that comes after it
ii) strip any trailing punctuation
iii) strip any square brackets

I don't think the order of step 2 and 3 really matter (nor do I know which way the parse does it)

Additional examples of what 245 might look like can be found on the LOC's MARC reference page: http://www.loc.gov/marc/bibliographic/bd245.html

Let me know if that clarifies things or if you need more.

**Comment by davekisly** [comment]
To clarify my earlier question, I'm asking not about the 245 tag itself, but more how the title (itself a single field) should be constructed where those multiple subfields are present? So, let's look at an example drawn from your test-set above:

`<marc:datafield tag="245" ind1="1" ind2="0">
<marc:subfield code="a">Social work in Canada</marc:subfield>
<marc:subfield code="b">an introduction,</marc:subfield>
<marc:subfield code="p">Volume 1,</marc:subfield>
<marc:subfield code="n">Student handbook /</marc:subfield>
<marc:subfield code="c">Steven Hick.</marc:subfield>
</marc:datafield>`

Currently, the parser appends the subfield b (where present) to the **end** of subfield a, as in this example:
- "Social work in Canada an introduction". 

Now that we want to parse the p and n fields, what should the expanded title look like? E.g.
- "Social work in Canada an introduction, Volume 1, Student Handbook"
- "Social work in Canada an introduction Volume 1 Student Handbook"
- "Social work in Canada an introduction, Student Handbook / Volume 1"

To my eye, the first or third looks best (there's other variations i didn't include), but its predicated on parsing in a specific order. What's your preference?

**Comment by Arty-chan** [comment]
@kpjorgen and @gitschatz can maybe chime in on this one, but I think the first would probably work best.

The way the titles are constructed in the repo right now though, I thought $b was appended to $a but without removal of punctuation. Resulting in:
"Social work in Canada : an introduction"

so including $np, it should actually look like this?
"Social work in Canada : an introduction, Volume 1, Student Handbook"

**Comment by davekisly** [comment]
Ok, i'll leave it to you (collectively) to let me know. 

My one point is that this specific example does not include a colon in the subfield a, so it would (if parsed now) be flattened out to "Social work in Canada an introduction".

If we should add colons between subfields a and b, is this something we should consider doing now while we're also addressing these other changes and fold it into your one-time update script?

**Comment by Arty-chan** [comment]
Sorry, I didn't realized the example didn't have the colon. We don't need to specifically add it. I just expected it to be there.

**Comment by Arty-chan** [comment]
realize the others are on vacation, so got SIO to contribute feedback.

Please go ahead with the discussed format.

**Comment by davekisly** [comment]
So, to confirm, when both subfields are present, we parse the $p first followed by the $n?

And, since you pointed me to the LOC docs, i will ask out of sadomasochistic due diligence if the ISBD principles are of any relevance here? E.g., those passages that describe $n and $p, including the last sentence (i've emboldened):

- $n "... In records formulated according to ISBD principles, subfield $n data follows a period (.) unless the last word in the [preceding] field is an abbreviation, initial/letter, or data that ends with final punctuation. Multiple alternative numberings for a part/section are contained in a single subfield $n."
- $p. "... In records formulated according to ISBD principles, subfield $p data follows a period (.) when it is preceded by subfield $a, $b or another subfield $p. **Subfield $p follows a comma (,) when it follows subfield $n**."

if any of this is relevant, then can you help interpret "when it follows subfield $n"? Would this mean when the $n subfield precedes the $p in the actual MARC record? I'm a bit confused b/c our single example above is as follows: `<marc:subfield code="p">Volume 1,</marc:subfield> <marc:subfield code="n">Student handbook /</marc:subfield>`

Walk me back from this cliff edge if the above is of no relevance here.

**Comment by Arty-chan** [comment]
Sorry if the example is confusing. I think the MARC record was not properly created (this is what happens when you copy someone else's record which errors in it!). The MARC record should be "$n, $p." (with the relevant data inside).

But it just goes to show that a lot of human errors make it into records. While we prefer the records to be properly formed, we don't always get properly formed records, so for 245, it might even be better to simply parse whatever is in $abnp "as is" (punctuation and order) and as per step ii) above, only strip trailing punctuation of the resulting title (not trailing punctuation of subfields).

The other option would be to strip trailing punctuation for all subfields then add our own when appending the subfields, but that seems like a lot more work and would have to take into consideration when $np does or does not exist.

Just to be clear, this would not affect step iii) since stripping all [ and ] should happen regardless.

I've fixed the punctuation in the record (hopefully correctly) and order of $np in the relevant 245 and uploaded the new version of the test set to staging.

**Comment by davekisly** [comment]
hi @Arty-chan - just to follow-up, if the idea is to **always** parse $n first and then $p, regardless of the order they appear in the MARC record, then that's no problem. I can treat the 245 as a whole unit, the subfields of which are parsed in a specific order. 

So, if that's the appropriate approach for the parser, i would not bother fixing / re-ordering MARC records in which the $p precedes the $n.

On the other hand, if the order in which these subfields are arranged in the MARC record is significant, then yes, i guess it would make sense to re-order the ones that are awry.

As a side-point, do you know if any of the record-sets include a handful of records with those subfields? Working with one sample record doesn't give me much to test with.

**Comment by Arty-chan** [comment]
the problem is that $n and $p are repeatable and can appear before or after certain other subfields where you definitely do not want to reorder them. Though rare, you can get things like the example on the LOC MARC page:
> $aAnnual report of the Minister of Supply and Service Canada under the Corporations and Labour Unions Returns Act.$nPart II,$pLabour unions =$bRapport annuel du ministre des Approvisionnements et services Canada présenté sous l'empire et des syndicates ouvriers.$nPartie II,$pSyndicats ouvriers.

The order is important, and while the specifications say $n should proceed $p, in terms of the resulting data, I don't think it'll make much difference since it's all going into the title.

So while it may introduce some human error (basically the same human error that is in the original MARC records), I would say that it's probably best to parse the record "as is" but only including subfields $abnp in the title in whatever order they appear in the original 245.

I imagine this would also simplify things should for any reason we want to parse more subfields in the future.

**Comment by davekisly** [comment]
It actually complicates (not simplifies) the parser. To explain, the parser loops thru an array of codes to concatenate the title in a sequence of subfields for a given tag (via xpath). 

You can see it here in my recently committed update: https://github.com/BCLibCoop/nnels-drupal-modules-cals_importer/blob/master/cals_importer.mappings.inc#L25-L45

If it needs to iterate thru the children in the "as-is" order, that's fine. Will just need to reconstruct this function.

**Comment by Arty-chan** [comment]
What about changing the function so that as it sees each subfield, check whether that subfield matches the list of subfields we want to keep?

Something similar to this maybe?:
```
function _cals_get_title_from_marc($xml, $k, &$map) {
  $codes = array("a", "b", "n", "p");
  $title = array();
  $subfield_path = "//marc:datafield[@tag='245']/marc:subfield";
  $subfield_nodes = $xml->xpath($subfield_path);

  foreach($subfield_nodes as $subfield) {
    if(in_array($subfield->get("code"), $codes) {
      $title[] = $subfield->text();
    }
  }

  $title = implode(" ", $title);
  $title = _cals_get_truncated_value($title, 250);
  if(strlen($title)) $map[$k]['values'][] = $title;
}
```
Though that's without knowing the XML API so the actual function names will likely be wrong.

**Comment by davekisly** [comment]
i've got something i'll commit shortly. Looks to work on the single record, but will be good to test w/ other examples. Back to you in 5 minutes.

**Comment by davekisly** [comment]
ok, here's a the same test record on DEV: https://dev.nnels.ca/items/social-work-canada-introduction-2

The parser generates this title: "Social work in Canada : an introduction. Student handbook, Volume 1" <- does that look appropriate?

**Comment by Arty-chan** [comment]
I assume you mean this one: https://dev.nnels.ca/items/social-work-canada-introduction-student-handbook-volume-1

Looks good. If you're looking for more test records... I can't tell you which ones specifically, but many of the Crane titles will have $np

**Comment by davekisly** [comment]
Yep, sorry that's the one. If you can point me to a good Crane collection likely to have these type of records, it will help. 

Questions re. Alternate and Uniform titles:

1. Re. "Similarly, Alternate Title should pull from 246 if the first indicator is 1 or 3, subfields $abnp"
 * i've got this more or less figured out. Should trailing punctuation be stripped out on this one as well? In other words, do we apply the same normalization as to the Title field?
2. Re. "Uniform title should pull from 130 $anp or if 130 does not exist, 240 where first indicator is 1, subfields $anp"
 * i don't think we have a "uniform" title field in the repo item. Should i add one?
 * and if yes, do we apply same normalization as the Title field?
3. Do either of these fields get pulled into public displays?

**Comment by Arty-chan** [comment]
This one should do it: https://staging.nnels.ca/admin/content/cals/records-sets/crane

There are more "Crane" record sets on PROD that are 500 records each.

**Comment by davekisly** [comment]
As an addendum to the question re. normalizing the secondary title fields (alternate, uniform), when i parse the record (on my local), it returns "Canadian Social work, Student handbook." for the alternate title. 

Is this appropriate or do you prefer the trailing period to be stripped off? I don't know what the convention is for Alternate & Uniform titles...

**Comment by Arty-chan** [comment]
Yes, let's apply the same normalization to Alternate and Uniform titles.

Uniform title is actually fairly rare, but should not only be its own field, but where the term is indexed (to allow auto-complete). Also, whereas there may be more than one alternate title, there can only ever be one uniform title.

**Comment by davekisly** [comment]
A few more questions:

1. Alternate titles: 
 - based on what you are saying, will some MARC records include multiple 246 tags? Or, are some of the subfields to be treated as discrete Alt Titles? I assume the former (multiple 246 tags), but want to make this explicit.
 - do we iterate through each 246 subfield in the "as-is" order (as the case for Titles)? Or, can i target the $anp subfields in a specific order each time? (The latter is slightly more performant, hence the question.)
2. Uniform title: 
 - Again, do we iterate over in the "as-is" order (as w/ Titles)?
 - i'm not certain i understand the "auto-complete" function: is this to be applied when the user is adding a new entry? If yes, auto-complete is typically only applied to Taxonomy fields ... but is that appropriate here? 
3. Do either of these fields get folded into the end-user search-result or node displays?

**Comment by Arty-chan** [comment]
1) Alternate title: since it's based off of 246 and 246 is a repeatable field, then potentially there will be more than one entry.
2) Uniform title: the whole point of Uniform title is that it acts as a link between multiple books (usually different editions) in the case that over time they've been called multiple things, but actually refer to the same book (e.g. The Hobbit / There and Back Again), so I believe that a Taxonomy field is worth having. Again, it's rare, so I can't imagine we will be indexing very many of these.

These will need to be ordered "as is" as well, because as with title, the order is not always predictable, especially with RDA coming into play.

3) I know at the they get indexed at least. As to whether we display it.. for now no, but possibly in the future.

**Comment by davekisly** [comment]
Ok, on my local i think i've got the basic logic figured out for all the title fields (title, alternate, uniform). 
<img width="510" alt="screen shot 2015-12-22 at 6 15 05 pm" src="https://cloud.githubusercontent.com/assets/852550/11968230/fef4a75c-a8d7-11e5-9d5e-b9c3c0cd87ea.png">


Iterating thru multiple alternate titles got a little ugly: the parsing gets a little convoluted and i couldn't find any quick "real" samples, so i had to create a couple fakes. Likewise, i couldn't find any real uniform titles in the 500 record-set i was using, so i ended up modifying a couple marc records to add some in.

So far, so good. I'll upload to DEV tomorrow so you can begin testing more thoroughly. You might want to create a record-set that includes some of the variations you want to test for.

**Comment by Arty-chan** [comment]
Okay, thanks.

**Comment by davekisly** [comment]
I've pulled the updates to DEV, but the VBO keeps failing. Not certain why as it works on my local with the same recordset: https://dev.nnels.ca/admin/content/cals/records-sets/crane-test

Might be some background process (as we've seen on Prod). I don't have time to troubleshoot now (xmas shopping, argh!!), but what u might do is parse individual items that you know will have Alternate and/or Uniform titles. You can figure this out by DL'ing the xml source file and hunting for the corresponding tags.

Alternatively, you could add your own tags to various records, save and then re-upload the file (similar to how i tested on my local).

**Comment by Arty-chan** [comment]
Unfortunately it looks like individual record parsing isn't working either. I tried both doing it from the record set view and from the individual item view, and neither worked.

Set: https://dev.nnels.ca/admin/content/cals/records-sets/title-alternative-and-uniform-test-using-crane-records
Item: https://dev.nnels.ca/items/sir-perceval-galles-and-ywain-and-gawain-0

**Comment by davekisly** [comment]
Yep, turns out one issue is that the Prod DB (which i'm using locally) has different vocabs vs. Dev's (which was throwing off the parser), so i've just committed code to check the specific Vocab IDs via a db lookup. Am currently re-running the code on the Crane test set - just did the first 50 of 500 with no issue. 

Please test again and let me know. I won't have much time for further refinements until next week, but any specific feedback you can provide will help.

**Comment by Arty-chan** [comment]
thanks. Looks like it's working as expected.

**Comment by Arty-chan** [comment]
Sorry, one thing it's not doing is removing the square brackets: https://dev.nnels.ca/admin/content/cals/records-sets/test-set

**Comment by davekisly** [comment]
- 250a is now parsing, but i am myself confused by the 3 fields that make up the field collection (Drupal side) in question. Only 2 fields are currently populated (value & qualifer, not value (term)). And, i have not applied any normalization / punctuation corrections. Please review and advise. 
- Re. "We will also need to run a one-time script to populate the repo-item metadata from existing MARCXML", i assume this was specifically in reference to the titles + edition statement? In any case, rather than add another one-time / single-field(s) parser, i opted for a more flexible solution that effectively facilitates re-parsing of any selected field(s). This took a bit of code refactoring, but in the end, its more streamlined than writing different parsers for different fields. Please test thoroughly, however, for regression errors and the like. Here's a view for re-parsing: https://dev.nnels.ca/admin/content/cals/repo-items/titles-alternate-uniform
- wrt the view above, note that you can filter on the basis of tags included in the original MARCXML - e.g., marc:datafield tag="246" - here's an example: https://dev.nnels.ca/admin/content/cals/repo-items/titles-alternate-uniform?keys=&field_xml_string_value=marc%3Adatafield%20tag%3D%22246%22&field_access_restrictions_value=All&field_record_set_nid=All&field_title_alternate_value_op=longerthan&field_title_alternate_value=&sort_by=title&sort_order=ASC&items_per_page=50 - its not 100% reliable, but it got me some test samples fairly effective
- as a note to self, there's several changes that will need to be copied over to Prod: 
 - 2 views: the one correspoding to the above and an embedded view for DC relations (edition) details.
 - need to update the audit field collection to incorporate a new "Re-parsing" value
 - add "isVersionOf" as a qualifier value into the Relations field collection
 - add Uniform Titles taxonomy and corresponding field into Repo Item
 - modify Alternate Title to accept multiple values

**Comment by Arty-chan** [comment]
250a: the only normalization should be the same as others: strip square brackets and trailing punctuation. Ideally, not if it ends with "ed." but in all other cases. For reference, see examples: http://www.loc.gov/marc/bibliographic/concise/bd250.html

I was referring specifically to alternate title, uniform title, and edition, but your solution is definitely more flexible.

Also, apologies, I realize 246 should be pulled if the first indicator is 0, 1, or 3 (originally I said 1 or 3), but I hope that's easy enough to change.

From what I've tested, everything looks okay. Think the only thing left (other than more testing) would be the displaying of the edition statement.

**Comment by davekisly** [comment]
@Arty-chan - i'm one foot out the door and don't seem to be able to pull my latest changes (which i've pushed to github) down to the DEV. If you are able to do a git pull (and flush drupal's cache), you should see i) normalization on 250a (per description below) and 246 parsing on the three indicators (0|1|3).

Re. normalization on end of string sub-strings like " ed.", you can control much of this via the configurable stopwords interface i set up here: https://dev.nnels.ca/admin/config/cals_importer/normalization

Notice how i've added " ed." - in most cases, you don't really need to first space, but as it happens "ed" is a common word ending. By adding "ed." as a stopword, the parser will effectively skip stripping off periods on entries like "Abridged.", which obviously is not correct. I should really tighten this up, but i only noticed it about 5 minutes before committing my last changes for the evening.

Will try to git pull later tonight: github is giving me grief on ssh keys (i had to reset them last evening, it worked and now today its timing out on my pulls).

**Comment by Arty-chan** [comment]
no problem. Will wait for you to pull latest changes to dev.

**Comment by Arty-chan** [comment]
looks like it's doing the right thing

one note on square brackets. I didn't see any issues in the test set but I noticed on PROD that it only strips opening square brackets at the start of a line (or subfield?) and closing square brackets if it's at the end, sometimes leaving a closing square bracket in the middle of a field. Could you make sure that's considered in this new version of the normalization? Might have just been an issue with dates

**Comment by davekisly** [comment]
hi @Arty-chan - just so i'm clear on "...make sure that's considered", do you mean that middle of sentence square brackets should be left intact or are you asking that they be stripped out, as well?

**Comment by Arty-chan** [comment]
all square brackets should be stripped out

**Comment by davekisly** [comment]
Ok, i can't remember if we retained middle-sentence square brackets by design (e.g., if they formed part of the original title), so i'll need to review the code (tonight, tomorrow AM). But, if that were by design, its actually simpler to strip out all square brackets so it should be a simple(ish) fix.

**Comment by davekisly** [comment]
Cynthia - Kris just prompted me on this. Apologies on leaving this for so long (completely buried on other fronts). Will get back to you tomorrow w/ a full review. 

That said, you should be able to test this yourself on DEV by editing the MARC string field for one or two repository items. For example, you could add square brackets into a title field and re-run the parser for that single entry. If it strips out the brackets, we're gold.

**Comment by davekisly** [comment]
hi @Arty-chan - as a follow-up, you can test with this record: https://dev.nnels.ca/items/1q84
I have edited the source XML string, as follows:
- 245a tag = **1[Q8]4**
- 246a tag = **One [Q] \[eight\] \(four\)....**

When you parse the item, these are normalized to:
- title = **1[Q8]4**
- alternate title = **One Q eight \(four\)**

This quick test seems to confirm the parser/normalization strips out all square brackets. But, if you want to test further, simply editing the XML string as i've done is probably the simplest approach. Toward that end, i've moved the XML fieldset toward the top of edit interface on DEV (let me know if you want that reproduced on PROD as well).
<img width="1187" alt="screen shot 2016-02-13 at 10 05 59 am" src="https://cloud.githubusercontent.com/assets/852550/13028320/84b16896-d239-11e5-8ba3-0dce9a9ece92.png">

**Comment by Arty-chan** [comment]
Thanks.

I think we can leave the MARC XML string where it is in the Files section and clean that up later.

I think at this point, we've got title done. I've moved the edition stuff to a new issue.

**Comment by Arty-chan** [comment]
It looks like something is a little off with title alternate.

Reparse this record: https://nnels.ca/items/world-undone-story-great-war-1914-1918

And the years got stripped out completely. With the new version of the parser, it looks like it's stripping it out of the title too
Should be: "A world undone the story of the Great War, 1914 to 1918" but it's "A world undone the story of the Great War, to"

**Comment by Arty-chan** [comment]
Sorry forgot to add, it's not stripping out all numbers though, because this one is just fine: https://nnels.ca/items/heart-any-fate-westward-oregon-1845

**Comment by davekisly** [comment]
@Arty-chan - i've just pulled an updated version that i think addresses the issue. Please retest with the records in question - i.e., just go directly to https://nnels.ca/items/world-undone-story-great-war and run the parse again.

**Comment by Arty-chan** [comment]
That worked for title alternate (246), but not the "main" title (245)

**Comment by davekisly** [comment]
ah yes, i believe the main title was not re-parsed after the initial skeletal record creation. I don't recall the original rationale for this, but in any case, i've just adjusted the parser to include the title field when parsing the full record. Here's the original record re-parsed: https://nnels.ca/items/world-undone-story-great-war-1914-1918

Please test again and let me know if it works as expected.

**Comment by Arty-chan** [comment]
Okay, thanks. It looks like it's doing the correct thing now.
